// Every line the protection tools say, in one place so the voice is easy to adjust.

export const permLabels = {
  ManageChannels: "Quản lý kênh",
  ManageGuild: "Quản lý server",
  ViewAuditLog: "Xem nhật ký kiểm tra",
  ManageRoles: "Quản lý role",
  SendMessages: "Gửi tin nhắn",
  EmbedLinks: "Nhúng liên kết",
  ViewChannel: "Xem kênh",
  KickMembers: "Đuổi thành viên",
};

export const securityLines = {
  adminOnly: "Khoá cổng cả server mà đòi bấm bừa à? Cần quyền Administrator mới được đụng vào.",
  noGuild: "Lệnh này chỉ chạy trong server thôi đại ca.",
  missingPerms: (names) => `Thầu thiếu đồ nghề: ${names.join(", ")}. Cấp quyền rồi gọi lại, thầu không khoá cổng bằng tay không được.`,
  alreadyLocked: "Công trường đang khoá rồi đại ca. Muốn mở thì gõ `/khoakhan tat`.",
  notLocked: "Có khoá gì đâu mà mở. Cổng đang mở toang, như tâm hồn thầu.",
  lockedOn: (locked, verify, minutes) =>
    `🔒 Khoá công trường xong. ${locked} kênh chat bị cấm @everyone gửi tin${verify ? ", mức xác minh đã được nâng một bậc" : ""}. Tự mở sau ${minutes} phút, hoặc gõ \`/khoakhan tat\`.`,
  lockedNothing: "Không có kênh nào cần khoá (kênh nào cũng đã cấm @everyone gửi tin, hoặc thầu không đủ quyền với chúng).",
  unlocked: (restored, skipped) =>
    `🔓 Mở cổng rồi. Trả ${restored} kênh về đúng như trước${skipped ? `, bỏ qua ${skipped} kênh đã bị ai đó chỉnh tay hoặc đã biến mất (thầu không đụng vào)` : ""}.`,
  unlockFailed: (names) => `Có ${names.length} kênh thầu không trả lại được (${names.join(", ")}). Mở tay giùm nha.`,
  autoUnlocked: (minutes) => `🔓 Hết ${minutes} phút khoá, thầu tự mở cổng. Ai còn spam thì thầu khoá lại.`,
  lockFailed: "Discord không cho thầu khoá lúc này. Kiểm tra quyền Quản lý kênh của bot rồi thử lại.",
  saved: "Đã lưu cài đặt chống raid và chống xoá hàng loạt. Thầu canh cổng đây.",
  savedLog: "Đã lưu cài đặt nhật ký kiểm duyệt.",
  badChannel: "Kênh này thầu không gửi tin được. Chọn kênh khác hoặc cấp quyền xem và gửi tin cho bot.",
  statusTitle: "Tình trạng canh cổng",
  on: "bật",
  off: "tắt",
  none: "chưa chọn",
  alertChannelNote: "kênh hệ thống nếu chưa chọn",
  timeoutNote: "Thầu không nhận được thông báo timeout của người khác (Discord chỉ gửi cho bot khi có quyền đặc biệt), nên chỉ ghi các timeout do lệnh `/timeout` của thầu.",
  raidTitle: "🚨 Báo động raid",
  raidBody: (count, seconds) => `${count} người nhảy vào server trong ${seconds} giây. Nhìn giống đám đông đi phá công trường hơn là khách.`,
  raidActionAlert: "Chỉ báo động, thầu không đụng vào cài đặt nào.",
  raidActionVerify: (from, to) => `Đã nâng mức xác minh từ ${from} lên ${to}. Sẽ tự hạ lại khi hết khoá.`,
  raidActionLock: (count) => `Đã khoá ${count} kênh chat (cấm @everyone gửi tin).`,
  raidActionFailed: "Thầu muốn ra tay nhưng thiếu quyền, nên chỉ báo động.",
  raidAutoUnlock: (minutes) => `Tự mở khoá sau ${minutes} phút.`,
  unlockButton: "Mở khoá",
  stale: "Nút này đã cũ, không còn khoá nào để mở.",
  verifyNames: ["Không", "Thấp", "Vừa", "Cao", "Rất cao"],
  nukeTitle: "💥 Báo động xoá hàng loạt",
  nukeBody: (userId, count, seconds) => `<@${userId}> vừa xoá ${count} kênh hoặc role trong ${seconds} giây. Thầu chưa từng thấy ai phá nhà nhiệt tình vậy.`,
  nukeStripped: (roles) => `Đã gỡ các role nguy hiểm: ${roles}. Admin cấp lại thủ công nếu đây là nhầm lẫn.`,
  nukeNothing: "Không gỡ được role nào (không có role nguy hiểm, hoặc nằm trên role của bot).",
  nukeKept: (list) => `Không đụng vào: ${list}.`,
  nukeNoAudit: "Thầu cần quyền Xem nhật ký kiểm tra thì mới biết ai xoá. Chưa có quyền này nên chống xoá hàng loạt đang ngủ.",
  nukeNoManage: "Thầu thiếu quyền Quản lý role nên chỉ báo động, không gỡ role được.",
  youngTitle: "🍼 Tài khoản mới toanh",
  youngBody: (userId, days, min) => `<@${userId}> vừa vào với tài khoản mới tạo được ${days} ngày, chưa đủ ${min} ngày thầu đặt ra. Nhìn giống hàng lập tối qua để phá hơn là khách quen.`,
  youngAlertOnly: "Chỉ báo cho đại ca biết, thầu không đụng tới ai.",
  youngKicked: "Đã mời ra khỏi công trường. Đủ tuổi thì quay lại sau.",
  youngKickFailed: "Thầu định mời ra nhưng Discord không cho, nên chỉ báo thôi.",
  youngKickPerm: (names) => `Thầu muốn mời ra nhưng thiếu quyền: ${names.join(", ")}. Cấp quyền rồi lần sau thầu làm được.`,
  youngKickRefused: {
    owner: "Đây là chủ server, thầu không dám đụng.",
    bot: "Đây là bot, thầu không đuổi.",
    welcomed: "Người này đã có role từ bước chào mừng.",
    above: "Role của người này ngang hoặc trên role của thầu nên thầu không đuổi được.",
  },
  youngStatusOff: "tắt",
  youngStatus: (days, action) => `dưới ${days} ngày sẽ ${action === "kick" ? "bị đuổi (và báo động)" : "chỉ báo động"}`,
  youngSaved: "Đã lưu bộ lọc tài khoản mới.",
  youngKickWarn: (names) => `Lưu ý: thầu đang thiếu quyền ${names.join(", ")} nên chưa đuổi được, hiện chỉ báo động.`,
  keptWhy: { managed: "role của bot", above: "ngang hoặc trên role của bot" },
};
