// Every line the ticket system says, in one place so the voice is easy to adjust.

export const ticketLines = {
  notConfigured: "Hệ thống ticket chưa cài xong. Admin cần chạy `/ticket caidat` chọn kênh bảng và role staff trước.",
  disabled: "Ticket đang tắt. Gọi admin bật lại bằng `/ticket dang`, chứ thầu đâu có mở cửa được.",
  noType: "Loại ticket này không còn nữa. Bấm lại nút trên bảng mới nhất.",
  cooldown: (seconds) => `Từ từ thôi đại ca, đợi ${seconds} giây nữa rồi hãy mở ticket tiếp. Staff không phải siêu nhân.`,
  tooMany: (max) => `Bạn đang mở ${max} ticket rồi, đóng bớt đã. Mở nhiều không làm staff trả lời nhanh hơn đâu.`,
  badReason: "Lý do trống trơn hoặc dài quá 300 ký tự. Viết ngắn gọn thôi, staff không có cả ngày.",
  noPerms: "Thầu thiếu quyền Quản lý kênh hoặc Quản lý role nên không tạo được kênh ticket. Báo admin cấp quyền giùm.",
  createFailed: "Discord không cho thầu tạo kênh ticket lúc này. Thử lại sau chút, hoặc báo admin kiểm tra danh mục và quyền bot.",
  opened: (channelId) => `🎫 Ticket của bạn đây: <#${channelId}>. Vô đó kể khổ đi, staff sẽ tới.`,
  welcome: (userId, staffRoleId) =>
    `Chào <@${userId}>, staff ${staffRoleId ? `<@&${staffRoleId}> ` : ""}sẽ vào sớm thôi. Trong lúc chờ, kể rõ vấn đề giùm, đừng chỉ gõ "alo".`,
  stale: "Ticket này không còn hợp lệ nữa (đã xoá hoặc không thuộc kênh này). Đừng thử bấm nút cũ.",
  notStaff: "Nút này của staff. Bạn muốn làm staff thì xin admin, đừng xin thầu.",
  notAllowed: "Ticket của người khác, bạn không đóng được. Đụng vô là staff tìm đó.",
  alreadyClaimed: (userId) => `<@${userId}> nhận ticket này trước rồi, giành làm gì.`,
  claimed: (userId) => `🙋 <@${userId}> đã nhận ticket này. Có người lo rồi, yên tâm.`,
  alreadyClosed: "Ticket này đóng rồi, đừng đóng thêm lần nữa.",
  notClosed: "Ticket này còn đang mở, chỉ ticket đã đóng mới xoá hoặc mở lại được.",
  closedNotice: (userId, reason) =>
    `🔒 Ticket đã đóng bởi <@${userId}>${reason ? `. Lý do: ${reason}` : ""}. Người mở không còn thấy kênh này. Staff chọn xoá kênh hoặc mở lại.`,
  closedReply: "Đã đóng ticket. Cảm ơn đã làm phiền, hẹn gặp lại ở vấn đề sau.",
  autoClosed: "Im lặng quá lâu nên ticket tự đóng. Còn cần thì mở cái mới.",
  reopened: (userId) => `🔓 <@${userId}> đã mở lại ticket. Vấn đề này sống dai ghê.`,
  reopenFailed: "Mở lại được trong sổ nhưng không trả quyền xem cho người mở được (có thể họ đã rời server).",
  deleting: "🗑️ Xoá kênh ngay đây. Sổ ghi chép vẫn giữ, thầu không quên đâu.",
  closeModalTitle: "Đóng ticket kèm lý do",
  openModalTitle: (label) => `Mở ticket: ${label}`.slice(0, 45),
  reasonLabel: "Bạn cần gì? (ngắn gọn thôi)",
  closeReasonLabel: "Lý do đóng",
  logOpened: (id, type, userId) => `🎫 Ticket #${id} (${type}) được mở bởi <@${userId}>.`,
  logClaimed: (id, userId) => `🙋 Ticket #${id} được <@${userId}> nhận.`,
  logClosed: (id, userId) => `🔒 Ticket #${id} đóng bởi <@${userId}>.`,
  logReopened: (id, userId) => `🔓 Ticket #${id} được <@${userId}> mở lại.`,
  logDeleted: (id, userId) => `🗑️ Kênh của ticket #${id} bị <@${userId}> xoá.`,
  panelTitle: "🎫 Cần hỗ trợ?",
  panelBody: "Bấm nút đúng loại bên dưới, điền lý do ngắn, thầu mở kênh riêng chỉ bạn và staff thấy. Spam nút thì thầu bắt đợi 30 giây.",
  ticketFooter: (id) => `Ticket #${id}`,
};

export const ticketCommandLines = {
  needTickets: (message) => message,
  badStaffRole: "Role staff không được là @everyone hay role của bot. Chọn role thật của đội ngũ, role đó chỉ được xem và gửi tin trong kênh ticket.",
  badChannel: "Kênh này thầu không dùng được, chọn kênh chữ thường.",
  saved: "✅ Đã lưu cài đặt ticket. Gõ `/ticket dang` để đăng hoặc cập nhật bảng.",
  needSetup: "Chưa đủ cài đặt: cần kênh đăng bảng và role staff. Gõ `/ticket caidat` trước.",
  typeLimit: "Tối đa 5 loại ticket thôi, nhiều hơn là staff khóc.",
  typeExists: "Loại này có rồi, đặt tên khác cho đỡ lẫn.",
  typeBadEmoji: "Emoji này Discord không nhận làm biểu tượng nút. Dùng emoji thường hoặc để trống.",
  typeAdded: (label) => `Đã thêm loại **${label}**. Gõ \`/ticket dang\` để cập nhật bảng.`,
  typeMissing: "Không thấy loại ticket tên đó.",
  typeLast: "Phải còn ít nhất một loại ticket, xoá hết thì bảng trống như ví cuối tháng.",
  typeRemoved: (label) => `Đã xoá loại **${label}**. Gõ \`/ticket dang\` để cập nhật bảng.`,
  panelFailed: "Thầu không đăng được bảng ở kênh đó. Kiểm tra quyền xem, gửi tin và nhúng link của bot.",
  panelPosted: (channelId) => `✅ Bảng ticket đã sẵn ở <#${channelId}>. Mở quán thôi.`,
  noOpen: "Chưa có ticket nào đang mở. Hiếm có khó tìm, tận hưởng đi.",
  off: "Đã tắt ticket. Ticket đang mở vẫn giữ nguyên, chỉ không nhận ticket mới.",
  listTitle: "🎫 Ticket đang mở",
};
