// Multiple-choice questions on safe, timeless facts. `answer` is the index of the right option.
// Options stay under 77 characters so "A. " plus the text fits a Discord button label (80 characters).
export const QUESTIONS = [
  { q: "Thủ đô của Việt Nam là thành phố nào?", options: ["Huế", "Hà Nội", "Đà Nẵng", "Cần Thơ"], answer: 1 },
  { q: "Đại dương nào lớn nhất thế giới?", options: ["Đại Tây Dương", "Ấn Độ Dương", "Thái Bình Dương", "Bắc Băng Dương"], answer: 2 },
  { q: "Đỉnh núi nào cao nhất thế giới so với mực nước biển?", options: ["Everest", "Fansipan", "Phú Sĩ", "Kilimanjaro"], answer: 0 },
  { q: "Thủ đô của Nhật Bản là thành phố nào?", options: ["Osaka", "Kyoto", "Nagoya", "Tokyo"], answer: 3 },
  { q: "Quốc gia nào có diện tích nhỏ nhất thế giới?", options: ["Monaco", "Vatican", "San Marino", "Malta"], answer: 1 },
  { q: "Vịnh Hạ Long thuộc tỉnh nào của Việt Nam?", options: ["Quảng Ninh", "Khánh Hòa", "Thanh Hóa", "Hải Dương"], answer: 0 },
  { q: "Fansipan được gọi là nóc nhà của khu vực nào?", options: ["Đông Nam Á", "Đông Dương", "Châu Á", "Thế giới"], answer: 1 },
  { q: "Dải đất Việt Nam có hình dáng giống chữ cái nào?", options: ["Chữ C", "Chữ L", "Chữ S", "Chữ U"], answer: 2 },
  { q: "Loài động vật nào lớn nhất thế giới?", options: ["Voi châu Phi", "Cá voi xanh", "Cá mập voi", "Hươu cao cổ"], answer: 1 },
  { q: "Con vật nào chạy nhanh nhất trên cạn?", options: ["Báo săn (cheetah)", "Sư tử", "Ngựa vằn", "Linh cẩu"], answer: 0 },
  { q: "Bạch tuộc có bao nhiêu trái tim?", options: ["1", "2", "3", "8"], answer: 2 },
  { q: "Loài động vật có vú nào biết bay thật sự?", options: ["Sóc bay", "Dơi", "Cầy bay", "Chim cánh cụt"], answer: 1 },
  { q: "Loài chim lớn nhất còn sống hiện nay là gì?", options: ["Đại bàng", "Đà điểu", "Chim cánh cụt", "Thiên nga"], answer: 1 },
  { q: "Cá heo thuộc nhóm động vật nào?", options: ["Cá", "Lưỡng cư", "Động vật có vú", "Bò sát"], answer: 2 },
  { q: "Một con nhện có bao nhiêu chân?", options: ["6", "8", "10", "12"], answer: 1 },
  { q: "Cơ quan nào bơm máu đi khắp cơ thể người?", options: ["Phổi", "Gan", "Thận", "Tim"], answer: 3 },
  { q: "Người trưởng thành có bao nhiêu chiếc xương?", options: ["206", "106", "306", "256"], answer: 0 },
  { q: "Cơ quan lớn nhất của cơ thể người là gì?", options: ["Gan", "Phổi", "Da", "Ruột non"], answer: 2 },
  { q: "Cơ thể tự tạo ra loại vitamin nào khi da tiếp xúc với ánh nắng?", options: ["Vitamin C", "Vitamin A", "Vitamin B12", "Vitamin D"], answer: 3 },
  { q: "Thành phần nào của máu chủ yếu vận chuyển oxy?", options: ["Hồng cầu", "Bạch cầu", "Tiểu cầu", "Huyết tương"], answer: 0 },
  { q: "Hành tinh nào gần Mặt Trời nhất?", options: ["Sao Kim", "Sao Thủy", "Trái Đất", "Sao Hỏa"], answer: 1 },
  { q: "Hành tinh nào được gọi là Hành tinh Đỏ?", options: ["Sao Hỏa", "Sao Mộc", "Sao Thổ", "Sao Kim"], answer: 0 },
  { q: "Trái Đất quay một vòng quanh Mặt Trời hết khoảng bao lâu?", options: ["Một ngày", "Một tháng", "Khoảng 365 ngày", "Mười năm"], answer: 2 },
  { q: "Mặt Trăng là gì của Trái Đất?", options: ["Hành tinh", "Sao chổi", "Ngôi sao", "Vệ tinh tự nhiên"], answer: 3 },
  { q: "Hành tinh nào nổi tiếng nhất với hệ thống vành đai?", options: ["Sao Thổ", "Sao Hải Vương", "Sao Thủy", "Sao Hỏa"], answer: 0 },
  { q: "Hệ Mặt Trời có bao nhiêu hành tinh theo cách phân loại hiện nay?", options: ["7", "8", "9", "10"], answer: 1 },
  { q: "Món bánh gói bằng lá dong, thường có trong ngày Tết ở miền Bắc, là gì?", options: ["Bánh chưng", "Bánh bao", "Bánh xèo", "Bánh cuốn"], answer: 0 },
  { q: "Áo dài là trang phục truyền thống của nước nào?", options: ["Trung Quốc", "Hàn Quốc", "Thái Lan", "Việt Nam"], answer: 3 },
  { q: "Món phở có nguồn gốc từ nước nào?", options: ["Việt Nam", "Lào", "Campuchia", "Thái Lan"], answer: 0 },
  { q: "Món bún chả nổi tiếng gắn liền với thành phố nào?", options: ["Huế", "Hải Phòng", "Hà Nội", "Đà Lạt"], answer: 2 },
  { q: "Nước mắm truyền thống được làm chủ yếu từ nguyên liệu nào?", options: ["Tôm khô", "Cá", "Đậu nành", "Mực"], answer: 1 },
  { q: "Loại cà phê nào được trồng nhiều ở Tây Nguyên của Việt Nam?", options: ["Arabica", "Robusta", "Liberica", "Moka"], answer: 1 },
  { q: "Một năm nhuận có bao nhiêu ngày?", options: ["364", "365", "366", "367"], answer: 2 },
  { q: "Một ngày có bao nhiêu phút?", options: ["1.200", "1.440", "1.600", "2.400"], answer: 1 },
];
