import type { Dict } from "./types";

const en: Dict = {
  lang: "en",
  meta: {
    title: "Thau Xay Dung, the Discord bot that builds a whole server in one command",
    description:
      "Invite the bot to an empty server, run /build or describe your group to an AI, review the blueprint, edit it, then build. Channels, roles, rules and a welcome, all of it ridiculous. Channel names stay in Vietnamese.",
  },
  nav: {
    how: "How it builds",
    themes: "Blueprints",
    pricing: "Plans",
    commands: "Commands",
    faq: "FAQ",
    devlog: "Devlog",
    cta: "Invite the contractor",
    switchTo: "VI",
    switchHref: "/",
    theme: "Toggle light and dark theme",
    home: "Back to top",
  },
  hero: {
    title: "Your server is as empty as a wallet at month's end.",
    sub: "Invite the contractor and run /build, or describe your group to an AI. A few minutes later your server has channels, roles, rules and some loving insults. Not inspected yet, but go ahead and use it.",
    cta: "Invite the contractor",
    secondary: "Watch the construction",
    commandLabel: "Blueprint waiting for a command",
    empty: "No channels yet. No rules yet. Nobody to argue with yet.",
  },
  scene: {
    title: "From bare ground to a finished server.",
    steps: [
      { t: "Call the contractor", d: "An admin runs /build and picks one or more themes. The bot posts a blueprint for approval first and touches nothing yet." },
      { t: "Pour the role foundation", d: "A Chairman, Mods, a Slave Bot and a few self-assign roles, each with a name nobody will admit to choosing." },
      { t: "Raise the channels", d: "Categories, text channels, voice rooms, and mod-only channels only mods can see. Announcement and rules channels are locked to read-only." },
      { t: "Post the rules", d: "Rules, a welcome and a role-picker with buttons land in the right channels. The DJ and text-to-speech rooms come with invite buttons." },
      { t: "Sign-off", d: "Done. Running /build again creates no duplicates, and /nuke removes exactly what the bot built." },
    ],
    cmd: "/build theme: Game Thủ Cày Đêm",
    roles: "Roles",
    rules: "Server rules",
    stamp: "Signed off",
    done: "done",
  },
  ai: {
    title: "Describe your group, an AI builds your server.",
    sub: "Not into the built-in themes? Tell the contractor who your group is and what it likes. Google Gemini comes up with categories, channels, roles, rules and a welcome that fit, then you review and edit it before anything is built.",
    inputLabel: "You type",
    description: "Group of 8 college friends, play Valorant on Saturday nights and chat a lot",
    levelLabel: "Humor level",
    levels: ["Gentle", "Troll", "Absurd"],
    resultLabel: "The AI returns",
    sampleNote: "A real answer from one run at the Troll level, trimmed. Every run gives a different result. The AI writes in Vietnamese.",
    plan: "Available from the Pro plan. Each server has a monthly number of AI designs.",
  },
  editor: {
    title: "Review, edit, then build.",
    sub: "Both /build and /thietke show you the whole channel tree before anything is created. No click can reshape your server by surprise.",
    points: [
      { t: "Remove a category", d: "Do not need a section? Drop it from the blueprint with one menu." },
      { t: "Rename", d: "Rename a category to match your group's voice." },
      { t: "Add a channel", d: "Add a text channel or voice room of your own." },
      { t: "Confirm", d: "Only the person who ran the command, and only an administrator, can press build. A blueprint expires after 15 minutes." },
    ],
    mockLabel: "Blueprint: Tổ Đội Bắn Trượt",
    removeLabel: "Remove a category",
    renameLabel: "Rename a category",
    add: "Add a channel",
    build: "Build it, boss",
    cancel: "Let me think",
    footer: "6 categories, 24 channels, 9 roles. The blueprint expires after 15 minutes.",
  },
  themes: {
    title: "Pick a blueprint.",
    sub: "Four themes. The shared part (admin area, DJ rooms, mod backstage) comes with every one.",
    items: [
      { id: "gaming", label: "Late-Night Gamers", blurb: "For gaming crews: a team finder, a clip showcase and a place to cry after a loss." },
      { id: "hoc-tap", label: "Studying Without Studying", blurb: "For study groups: homework help, burning deadlines, an exam-eve room." },
      { id: "cong-dong", label: "General Store Community", blurb: "For any community: chatter, photo sharing, events and assorted odds and ends." },
      { id: "chill-ban-be", label: "Chill With the Crew", blurb: "For close friends: an archive of each other's bad photos and plans nobody follows." },
    ],
    rolesLabel: "Sample roles",
    channelsLabel: "Theme-only channels",
    sharedLabel: "Shared by every theme",
    tablist: "Choose a theme",
    mixNote: "Studying, gaming and chilling all at once? The Pro plan mixes up to 4 themes in one server, and channels with the same name appear once.",
  },
  rules: {
    title: "Rules nobody reads, but everyone gets reminded of.",
    sub: "Eight shared rules plus two per theme, posted into the rules channel. A few samples (in Vietnamese, as the bot writes them):",
  },
  music: {
    title: "What about music and text-to-speech?",
    body: "Discord does not let a bot invite another bot, only a person can. So the contractor does what it can: it builds the DJ room, the karaoke room and the text-to-speech room, and puts an invite button for a music bot and a TTS bot right in the channel. An admin clicks once and the music starts.",
    points: ["#dj-booth has a music bot invite button", "#chém-gió-bằng-giọng has a TTS bot invite button", "You configure the bot links, the contractor just places the buttons"],
  },
  pricing: {
    title: "Three plans, paid per server.",
    sub: "One plan per server. Buy an activation code, run /kichhoat, use it right away. When it ends the server returns to the free plan and what was already built stays.",
    plans: [
      {
        id: "free",
        name: "Free",
        price: "$0",
        blurb: "To see how the contractor works.",
        features: ["1 built-in theme", "1 build", "Review and edit the blueprint", "/nuke to clean up", "No AI"],
      },
      {
        id: "pro",
        name: "Pro",
        price: "$4.99 / 30 days",
        blurb: "For groups that want a server that fits them.",
        features: ["Mix up to 4 themes", "Unlimited builds", "AI design: 20 per month", "Pick the humor level", "Review and edit the blueprint"],
      },
      {
        id: "plus",
        name: "Plus",
        price: "$9.99 / 30 days",
        blurb: "For people who build many servers.",
        features: ["Everything in Pro", "AI design: 100 per month"],
      },
    ],
    howTitle: "How to buy",
    how: ["Message the bot owner on Instagram with the plan and number of days you want", "Pay as instructed and receive a code like THAU-XXXX-XXXX-XXXX", "Run /kichhoat ma:<code> in your server. A code works once, and a second code of the same plan adds its days"],
    contact: "Message on Instagram to buy a code",
    note: "Prices are in US dollars, per server, per 30 days. Customers in Vietnam pay the VND equivalent at the exchange rate on the day. Want more days? Message to work it out. There are no automatic payments yet.",
  },
  commands: {
    title: "Seven commands for customers, no more.",
    items: [
      { name: "/build", args: "theme theme2 theme3 theme4", d: "Builds the server from one or more themes. Shows an editable blueprint and asks for confirmation. Admins only." },
      { name: "/thietke", args: "mota muc-do-hai", d: "An AI designs your own server from a description. From the Pro plan, with a monthly allowance." },
      { name: "/nuke", args: "", d: "Tears down what the bot built. Only touches channels and roles the bot created, with a confirm button." },
      { name: "/kichhoat", args: "ma", d: "Activates a paid plan for the server with a code you bought." },
      { name: "/goi", args: "", d: "Shows the current plan, how many builds were used and how to upgrade." },
      { name: "/xoadulieu", args: "", d: "The bot forgets the list of channels and roles it built. The channels and roles on Discord stay." },
      { name: "/roast", args: "nguoi", d: "Gently roasts a member for fun. Cannot mod, cannot mute, can only offend." },
    ],
  },
  faq: {
    title: "FAQ",
    items: [
      { q: "What permissions does it need?", a: "Whoever runs the command needs Administrator. The bot needs Manage Channels, Manage Roles and Manage Server, and must be able to post in the read-only channels it creates. The easy way is to invite it with Administrator." },
      { q: "Will it delete my existing channels?", a: "No. /build only adds, and channels with the same name are skipped. /nuke only removes what the bot itself created, by the IDs it recorded." },
      { q: "Does running /build twice create duplicates?", a: "No. What exists is skipped, and content like rules and the welcome is not posted again. The free plan allows one build, though." },
      { q: "Does the AI build straight into my server?", a: "Never. Its answer is cleaned (mentions and blocked words removed, counts capped) and shown as a blueprint for you to review and edit. Nothing is created until you press build." },
      { q: "Where does my group description go?", a: "The description you type is sent to Google Gemini to create the design, with no usernames or messages. The bot uses Google's free tier, so Google may use it to improve its products. Do not put anything private in it." },
      { q: "What does the bot store about my server?", a: "The IDs of the channels and roles it created, the active plan and usage counts for some features. It does not read message content. Run /xoadulieu so it forgets what it built." },
      { q: "Why does the music not come automatically?", a: "Because Discord forbids bots from inviting bots. The contractor puts the invite button in the DJ channel and you click it once." },
    ],
  },
  cta: {
    title: "Your server has waited long enough.",
    steps: ["Invite the contractor to your server (Administrator is easiest)", "Run /build or /thietke, review the blueprint, edit if you like", "Hit build and go make coffee"],
    button: "Invite the contractor",
    note: "",
    setupId: "setup",
  },
  footer: {
    word: "BUILT IT",
    privacy: "Privacy",
    terms: "Terms",
    devlog: "Build diary",
    source: "Source code",
    line: "A personal project, not affiliated with Discord. Ridiculous construction, no warranty.",
  },
};

export default en;
