import type { Dict } from "./types";

const en: Dict = {
  lang: "en",
  meta: {
    title: "Thau Xay Dung, the Discord bot that builds and looks after a whole server",
    description:
      "Invite the bot to an empty server, press Start or run /batdau, review the blueprint, then build. Channels, roles, rules, anti-raid, a mod log, giveaways and a weekly report, all of it ridiculous and none of it reading anyone's messages. Channel names stay in Vietnamese.",
  },
  nav: {
    how: "How it builds",
    themes: "Blueprints",
    pricing: "Plans",
    commands: "Commands",
    faq: "FAQ",
    devlog: "Devlog",
    status: "Status",
    cta: "Invite the contractor",
    switchTo: "VI",
    switchHref: "/",
    theme: "Toggle light and dark theme",
    home: "Back to top",
  },
  hero: {
    title: "Your server is as empty as a wallet at month's end.",
    sub: "Invite the contractor, press Start or run /batdau, or describe your group to an AI. A few minutes later your server has channels, roles, rules and some loving insults, and a guard at the gate when a raid hits. Not inspected yet, but go ahead and use it.",
    cta: "Invite the contractor",
    secondary: "Watch the construction",
    dim: "1 command, a few minutes",
  },
  plotter: {
    title: "Drafting table",
    chipsLabel: "Pick themes, mix as many as you like",
    hint: "Press to add or drop a theme. The tree below is the bot's real output for each mix.",
    proNote: "Mixing themes is a Pro feature. Channels with the same name appear once.",
    limit: "At most 4 themes at once, like the /build command.",
    categories: "categories",
    channels: "channels",
    roles: "roles",
    rules: "rules",
    build: "Try a build",
    done: "Signed off",
    summary: "{categories} categories, {channels} channels, {roles} roles",
  },
  scene: {
    title: "From bare ground to a finished server.",
    label: "How it builds",
    steps: [
      { t: "Call the contractor", d: "An admin runs /build and picks one or more themes. The bot posts a blueprint for approval first and touches nothing yet." },
      { t: "Pour the role foundation", d: "A Chairman, Mods, a Slave Bot and a few self-assign roles, each with a name nobody will admit to choosing." },
      { t: "Raise the channels", d: "Categories, text channels, voice rooms, and mod-only channels only mods can see. Announcement and rules channels are locked to read-only." },
      { t: "Post the rules", d: "Rules, a welcome and a role-picker with buttons land in the right channels. The DJ and text-to-speech rooms come with invite buttons." },
      { t: "Sign-off", d: "Done. Running /build again creates no duplicates, and /nuke removes exactly what the bot built." },
    ],
    cmd: "/build theme: Game Thủ Cày Đêm",
    roles: "Roles",
    rules: "Server rules",
    stamp: "Signed off",
  },
  ai: {
    title: "Describe your group, an AI builds your server.",
    label: "AI designer",
    sub: "Not into the built-in themes? Tell the contractor who your group is and what it likes. Google Gemini comes up with categories, channels, roles, rules and a welcome that fit, then you review and edit it before anything is built. Switch the humor level below to see three real answers.",
    inputLabel: "You type",
    description: "Group of 8 college friends, play Valorant on Saturday nights and chat a lot",
    levelLabel: "Humor level",
    levels: ["Gentle", "Troll", "Absurd"],
    resultLabel: "The AI returns",
    provenance: "All three are real answers, run on {date} with {model}. Every run gives a different result. The AI writes in Vietnamese.",
    plan: "Available from the Pro plan. Each server has a monthly number of AI designs.",
  },
  editor: {
    title: "Review, edit, then build.",
    label: "Blueprint",
    sub: "Both /build and /thietke show you the whole channel tree before anything is created. Next to this text is a working miniature that follows the bot's own rules: drop a category, rename one, add a channel, then press build.",
    points: [
      { t: "Remove a category", d: "Do not need a section? Drop it from the blueprint. The admin area stays, because the rules and welcome live there." },
      { t: "Rename", d: "Press a category name to rename it to your group's voice. Names cannot collide." },
      { t: "Add a channel", d: "Add a text channel or voice room of your own. A channel with an existing name is refused." },
      { t: "Confirm", d: "Only the person who ran the command, and only an administrator, can press build. A blueprint expires after 15 minutes." },
    ],
    tryLabel: "Try it right here",
    locked: "fixed",
    remove: "Drop",
    rename: "Rename category",
    renameHint: "Press to rename",
    addPlaceholder: "new channel name",
    text: "text",
    voice: "voice",
    add: "Add channel",
    build: "Build it, boss",
    reset: "Reset blueprint",
    counts: "{c} categories, {ch} channels",
    removed: "Dropped {name}.",
    renamed: "Category renamed.",
    added: "Added channel {name}.",
    duplicate: "That name already exists, left as it was.",
    building: "Building...",
    done: "Done, signed off.",
  },
  themes: {
    title: "Eleven built-in blueprints.",
    label: "Themes",
    sub: "The shared part (admin area, DJ rooms, mod backstage) comes with every theme. Each theme adds its own categories, channels, roles and two rules.",
    items: [
      { id: "gaming", label: "Late-Night Gamers", blurb: "For gaming crews: a team finder, a clip showcase and a place to cry after a loss." },
      { id: "hoc-tap", label: "Studying Without Studying", blurb: "For study groups: homework help, burning deadlines, an exam-eve room." },
      { id: "cong-dong", label: "General Store Community", blurb: "For any community: chatter, photo sharing, events and assorted odds and ends." },
      { id: "chill-ban-be", label: "Chill With the Crew", blurb: "For close friends: an archive of each other's bad photos and plans nobody follows." },
      { id: "booking", label: "Book a Friend", blurb: "For servers where people book a friend to play or talk: booking guide, price list, player profiles, feedback and scam protection." },
      { id: "anime", label: "Anime Fan Club", blurb: "For anime and manga fans: recommendations, reviews, spoilers behind a fence, fanart and waifu wars." },
      { id: "dev-code", label: "Wandering Coders", blurb: "For programmers: bug help, project showcase, code review, jobs and mourning the Friday afternoon deploy." },
      { id: "creator", label: "Creator Studio", blurb: "For streamers, YouTubers and TikTokers: ideas, video feedback, live schedule, collabs and honest numbers." },
      { id: "phim-nhac", label: "Cinema and Music Room", blurb: "For movie and music lovers: suggestions, votes for movie night, shared playlists and karaoke." },
      { id: "cong-so", label: "One-House Office", blurb: "For a company team or project group: announcements, today's tasks, deadlines and lunch-break chatter." },
      { id: "thu-cung", label: "Pet Lovers Club", blurb: "For people with dogs and cats: show off the boss, ask for care tips, find homes and share the household stories." },
    ],
    rolesLabel: "Own roles",
    sharedLabel: "Shared",
    mixNote: "Studying, gaming and chilling all at once? The Pro plan mixes up to 4 themes in one server. Try it on the drafting table above.",
  },
  features: {
    title: "Built is only the start.",
    label: "After the build",
    sub: "Building a new server is only day one. The rest keeps it safe and keeps your group around: protection, moderation, activity levels, giveaways, a suggestion box, temporary voice rooms, stats channels, scheduled messages, reminders, a weekly report, mini-games and recurring events. The bot never reads anyone's messages.",
    items: [
      { t: "Guided setup with /batdau", d: "When the bot joins it posts a Start button. Pick the kind of server, the tone and a few features to switch on, press one button: the server is built, the settings are in, and you get a health score before and after to show off. Not sure what to pick? Type a few words and the contractor suggests." },
      { t: "Anti-raid and emergency lockdown", d: "A crowd floods in at once? The contractor raises the alarm, then only alerts, raises the verification level or locks the chat channels, as you choose. Everything it changes is recorded and put back exactly as it was when time is up, or when you press Unlock." },
      { t: "Anti-nuke guard", d: "Someone deletes a pile of channels or roles? The contractor reads the audit log to see who, raises the alarm and takes that person's dangerous roles away. It never touches the owner or anyone at or above the bot's own role. Pro plan." },
      { t: "Mod log", d: "Who was banned, who was unbanned, which role changed permissions (what was added, what was removed), who AutoMod blocked and where. Written to a channel you pick, and never including the text of a blocked message." },
      { t: "Warn, timeout, kick, ban with case history", d: "Four commands that check the role order first, message the person, store a numbered case and write it to the log. /hoso shows a member's last ten cases." },
      { t: "Activity points and levels", d: "Chatting and sitting in voice both level you up, with a cooldown and a daily cap so nobody farms with spam. The bot only knows who wrote where, never a word of it. Pro plan." },
      { t: "Role menus with buttons", d: "Members press a button to take or drop a role, pick-one or pick-many. Only safe roles can go in a menu, and every press is checked again." },
      { t: "Giveaways and polls", d: "Giveaways with a Join button, a required role, several winners, an automatic draw when time is up and a reroll. Anonymous button polls, one vote each, results updated in place." },
      { t: "Temporary voice rooms", d: "Join a lobby channel and you get a voice room of your own, named after you. The owner can rename it and move people out, and an empty room cleans itself up. The contractor only deletes rooms it made and recorded. 1 lobby on Free, 3 on Pro, 5 on Plus." },
      { t: "Stats channels", d: "A voice channel whose name is a live number: members, boosts, channels or roles. It refreshes every 10 minutes because Discord limits how often a channel can be renamed, and the contractor can build a locked channel for you. Up to 4, and Free gets 1." },
      { t: "Suggestion box", d: "Anyone can send a suggestion, everyone votes up or down, and staff approve, reject or mark it done with a note. The author gets a private message with the result. One vote each, with limits against spam. Free." },
      { t: "Personal reminders", d: "Run /nhacviec, pick a delay or a clock time, and the contractor messages you privately at the right moment. Anyone can use it, free. If your DMs are closed it reminds you in the channel you used and mentions only you." },
      { t: "Scheduled messages", d: "A message posted on time every day or every week: the rules, a good morning, the study timetable. It never pings anyone, not even @everyone. You can preview it before scheduling. 5 on Pro, 15 on Plus." },
      { t: "New-account filter", d: "Set a minimum age for Discord accounts. Anyone who joins with a newer account triggers an alert, or a kick if you choose that. The owner, bots and anyone at or above the bot are never kicked. Free." },
      { t: "Your own blocked words", d: "Build a blocked word list for your server. The contractor writes it into Discord's native keyword rule, so Discord does the blocking and the bot never sees a message. 20 words on Free, 200 on Pro, 500 on Plus." },
      { t: "Weekly report and checks", d: "Once a week a summary goes to the mod channel: new members, tickets, AutoMod blocks, the health score against last week and three things to do. A sharp drop gets its own alert. It only counts numbers, never reads messages." },
      { t: "Reminders before a plan ends", d: "When a Pro or Plus plan is about to end the bot reminds you once three days ahead and once when it ends, and no more. Renewing adds the days on top." },
      { t: "Writing helper", d: "Not sure how to write the rules, a welcome or an announcement? Describe it in a few words and an AI drafts it. The contractor posts nothing itself, you read it and press post. It can also explain the health check in plain words. Pro plan." },
      { t: "Three humor levels", d: "The same server in three voices: gentle, troll, absurd. The shared rules and the welcome change their tone while the channel structure stays put, so rebuilding at another level creates no duplicates." },
      { t: "Your own themes", d: "Finish editing a blueprint and save it as your theme. Reuse it, export it to a file or import one from a friend. A saved theme never carries permissions." },
      { t: "Backup and restore", d: "Snapshot the server's structure: roles, channels, permissions. Restore only creates what is missing, deletes nothing, and never grants the Administrator permission." },
      { t: "Check-in, levels, mini-games", d: "Check in every day, level up with points, guess the number, rock paper scissors and quick trivia. There is a leaderboard for the whole group." },
      { t: "Recurring events", d: "Friday game night, Sunday study group: the bot creates the Discord events and reminds people ahead of time." },
      { t: "Automatic payments", d: "Run /mua, pay by card (Stripe) or with a Vietnamese bank QR code (payOS), and the plan switches on when the money arrives. Nobody has to send you a code." },
      { t: "Welcoming new members", d: "A new member gets a funny welcome, a starter role and a button to confirm they are human. The bot only reads Discord's join notice, never anyone's messages." },
      { t: "Server health check", d: "Scan a running server and get a score: @everyone holding dangerous permissions, missing rules, announcement channels anyone can write in. Safe fixes get a button, and you see exactly what will change first." },
      { t: "Discord's own AutoMod", d: "The contractor sets up Discord's built-in AutoMod at three levels, with funny block messages. The bot never has to read message content." },
      { t: "Web dashboard", d: "Sign in with Discord, pick your server and change the welcome, AutoMod, tickets, protection, activity points, weekly report and mod log, or read the health score in the browser. Only a server's administrators can see that server." },
      { t: "Support tickets", d: "A panel of buttons opens tickets, each in a private channel for the member and the staff, with claim and close, and auto-close when it goes quiet. No chat content is stored." },
      { t: "Every command at a glance", d: "/trogiup lists the commands in groups, marks which ones need a higher plan and links to the handbook." },
    ],
  },
  rules: {
    title: "Rules nobody reads, but everyone gets reminded of.",
    label: "Rules",
    sub: "Eight shared rules plus two per theme, posted into the rules channel. A few samples (in Vietnamese, as the bot writes them):",
  },
  music: {
    title: "What about music and text-to-speech?",
    label: "Music and TTS",
    body: "Discord does not let a bot invite another bot, only a person can. So the contractor does what it can: it builds the DJ room, the karaoke room and the text-to-speech room, and puts an invite button for a music bot and a TTS bot right in the channel. An admin clicks once and the music starts.",
    points: ["#dj-booth has a music bot invite button", "#chém-gió-bằng-giọng has a TTS bot invite button", "You configure the bot links, the contractor just places the buttons"],
  },
  pricing: {
    title: "Three plans, paid per server.",
    label: "Plans",
    sub: "One plan per server. Pay by card or bank QR code and the plan switches on when the money arrives. When it ends the server returns to the free plan and what was already built stays.",
    plans: [
      {
        id: "free",
        name: "Free",
        price: "$0",
        blurb: "To see how the contractor works.",
        features: ["1 built-in theme, 2 builds", "Guided setup with /batdau", "Review and edit the blueprint", "/nuke to clean up", "Welcoming new members", "Server health check", "Basic AutoMod", "Anti-raid, lockdown, mod log", "Warn, timeout, kick, ban with case history", "Polls and the weekly report", "3 role menus", "Suggestion box, personal reminders", "Temporary voice rooms (1 lobby), 1 stats channel", "New-account filter", "20 blocked words of your own", "No AI"],
      },
      {
        id: "pro",
        name: "Pro",
        price: "$3.99 / 30 days",
        blurb: "For groups that want a server that fits them.",
        features: ["Mix up to 4 themes, unlimited builds", "AI design: 20 per month", "Writing helper /vietgiup", "Pick the humor level", "Anti-nuke guard", "Activity points for chat and voice", "Giveaways", "10 role menus", "3 lobbies, 4 stats channels", "5 scheduled messages", "200 blocked words of your own", "3 backups, 3 saved themes", "Mini-games, levels, leaderboard", "3 recurring events", "AutoMod at three levels, link blocking", "Support tickets"],
      },
      {
        id: "plus",
        name: "Plus",
        price: "$7.99 / 30 days",
        blurb: "For people who build many servers.",
        features: ["Everything in Pro", "AI design: 100 per month", "25 role menus", "5 lobbies", "15 scheduled messages", "500 blocked words of your own", "10 backups", "10 saved themes", "10 recurring events"],
      },
    ],
    options: [
      { t: "Buy a year, pay ten months", d: "Pick 365 days: Pro is $39.90 and Plus $79.90. Two months free. 90 and 180 days are there too." },
      { t: "Build it for me, $4.99 once", d: "No subscription wanted? Pay once and get 7 days of Pro, enough to build and set the whole server up. Pick it in /mua." },
      { t: "Try Pro free for 7 days", d: "Run /dungthu, once per server, no card, no automatic renewal." },
    ],
    howTitle: "How to buy",
    how: ["Run /mua in your server (only an admin can), pick Pro, Plus or Build it for me and 30, 90, 180 or 365 days", "Press the Pay button and pay by card on Stripe's page, or scan the QR code with your banking app", "When the money arrives the plan switches on within about a minute, no code to enter"],
    contact: "Prefer a code? Message on Instagram",
    note: "Prices are in US dollars, per server, per 30 days, and a year counts as 10 months. You pay in Vietnamese dong at the rate the bot uses, and the price is shown before you pay. The alternative: message on Instagram to get a code like THAU-XXXX-XXXX-XXXX and run /kichhoat.",
  },
  commands: {
    title: "The contractor's commands.",
    label: "Commands",
    hint: "press to copy",
    copied: "copied",
    items: [
      { name: "/batdau", args: "", d: "Builds and sets up the whole server with three menus and one button: the kind of server, the tone, the features to switch on. Admins only." },
      { name: "/trogiup", args: "", d: "The commands in groups, with the ones that need a higher plan marked, and a button to the handbook." },
      { name: "/build", args: "theme theme2 theme3 theme4 muc-do-hai", d: "Builds the server from one or more themes at the humor level you pick. Shows an editable blueprint and asks for confirmation. Admins only." },
      { name: "/thietke", args: "mota muc-do-hai", d: "An AI designs your own server from a description. From the Pro plan, with a monthly allowance." },
      { name: "/vietgiup", args: "luat loichao thongbao giaithich", d: "An AI drafts the rules, a welcome, an announcement, or explains the health check. It never posts by itself. From the Pro plan." },
      { name: "/theme", args: "danhsach dung xoa xuat nhap", d: "Reuse, export and import the themes you saved from a blueprint. From the Pro plan." },
      { name: "/backup", args: "tao khoiphuc danhsach xoa xuat nhap", d: "Back up the server's structure and restore what is missing. From the Pro plan." },
      { name: "/sukien", args: "tao danhsach xoa mau", d: "Create weekly recurring events; the bot schedules and announces them. From the Pro plan." },
      { name: "/diemdanh", args: "", d: "Check in every day for points and keep your streak. From the Pro plan." },
      { name: "/bangxephang", args: "loai", d: "The top 10 for fun points or for activity, and everyone's level." },
      { name: "/doanso", args: "so", d: "Guess a number from 1 to 100, the whole server guesses, the winner gets points." },
      { name: "/thachdau", args: "nguoi", d: "Challenge someone to rock paper scissors, the winner gets points." },
      { name: "/cauhoi", args: "", d: "Quick trivia with four answers, the first correct press gets points." },
      { name: "/hang", args: "xem caidat", d: "See your activity level, points and rank (chat and voice). Admins switch it on and tune the numbers. From the Pro plan." },
      { name: "/vaitro", args: "tao dang danhsach xoa", d: "Role menus with buttons, pick-one or pick-many. Admins create them. 3 menus free, 10 on Pro, 25 on Plus." },
      { name: "/quatang", args: "tao huy chonlai danhsach", d: "Giveaways with a Join button, an automatic draw when time is up and a reroll. Needs Manage Server. From the Pro plan." },
      { name: "/binhchon", args: "cauhoi lua1 lua2 thoigian", d: "Anonymous button polls, one vote each, closed by a timer or a button. Needs Manage Messages." },
      { name: "/phongtam", args: "caidat them bo trangthai tat", d: "Temporary voice rooms: join a lobby to get a room of your own, and an empty room is cleaned up. Admins set it up. 1 lobby on Free, 3 on Pro, 5 on Plus." },
      { name: "/kenhthongke", args: "them xoa danhsach tat", d: "Voice channels that show a live count of members, boosts, channels or roles, refreshed every 10 minutes. Admins set it up. 1 channel on Free, 4 on Pro and Plus." },
      { name: "/gopy", args: "gui caidat danhsach xoa", d: "The server's suggestion box: anyone can send, everyone votes, staff decide. Setting it up needs Manage Server. Free." },
      { name: "/nhacviec", args: "tao danhsach xoa", d: "Ask the contractor for a private reminder by direct message, after a delay or at a clock time. Anyone can use it. Free." },
      { name: "/hengio", args: "tao danhsach xoa thu", d: "Schedule a message every day or every week, never pinging anyone, with a preview. Admins only. 5 on Pro, 15 on Plus." },
      { name: "/chaomung", args: "caidat thu tat", d: "Welcome new members with a funny message, a starter role and a verification button. Admins set it up." },
      { name: "/khamsuckhoe", args: "kiemtra lichsu", d: "Scan the server and score its health, with safe fixes you can preview." },
      { name: "/automod", args: "bat tat trangthai mientru tukhoa", d: "Set up Discord's own AutoMod at three levels, and keep your own blocked word list (tukhoa them, xoa, danhsach, xoahet) that Discord enforces. The strict level, link blocking and exemptions are Pro. Words: 20 on Free, 200 on Pro, 500 on Plus." },
      { name: "/khoakhan", args: "bat tat trangthai caidat nhatky", d: "Emergency lockdown, automatic anti-raid, a filter for brand-new accounts, the anti-nuke guard (Pro) and the mod log. Anything it locks is put back exactly as it was." },
      { name: "/canhcao", args: "nguoi lydo", d: "Warn a member and record it in their file. Needs Moderate Members." },
      { name: "/timeout", args: "nguoi thoigian lydo", d: "Silence a member from one minute to one week and record it. Needs Moderate Members." },
      { name: "/kick", args: "nguoi lydo", d: "Remove a member from the server and record it. Needs Kick Members." },
      { name: "/ban", args: "nguoi lydo xoatin", d: "Ban someone, optionally deleting their recent messages, and record it. Needs Ban Members." },
      { name: "/hoso", args: "nguoi", d: "A member's last ten moderation cases. Needs Moderate Members." },
      { name: "/ticket", args: "caidat loai dang danhsach tat", d: "A support ticket system with a button panel, private channels and auto-close. From the Pro plan." },
      { name: "/nuke", args: "", d: "Tears down what the bot built. Only touches channels and roles the bot created, with a confirm button." },
      { name: "/mua", args: "goi ngay cach", d: "Buy or renew Pro, Plus or the one-off Build it for me by card or bank QR code; it switches on when the money arrives." },
      { name: "/dungthu", args: "", d: "Try the Pro plan free for 7 days, once per server." },
      { name: "/kichhoat", args: "ma", d: "Activates a paid plan for the server with a code you bought." },
      { name: "/goi", args: "", d: "Shows the current plan, how many builds were used, the prices and how to upgrade." },
      { name: "/xoadulieu", args: "", d: "The bot forgets everything it keeps about the server, including temporary room records, scheduled messages, reminders and suggestions, except billing records. The channels and roles on Discord stay." },
      { name: "/roast", args: "nguoi", d: "Gently roasts a member for fun. Cannot mod, cannot mute, can only offend." },
    ],
  },
  faq: {
    title: "FAQ",
    label: "FAQ",
    items: [
      { q: "Does the contractor read my messages?", a: "No. The bot does not read or store message content, does not use the Message Content permission and uses no privileged Discord intent. Activity points only use who wrote in which channel, the AutoMod log records which rule blocked whom without the blocked text, and the weekly report only counts numbers." },
      { q: "What is /batdau?", a: "The fastest way to set up: when the bot joins it posts a Start button, or you run /batdau. Pick the kind of server, the tone and a few features to switch on (welcome, gentle AutoMod, weekly health check, basic protection, weekly report) and press Build. The bot checks health first, builds, switches the features on, checks again and shows a result card with the before and after scores. Running it again creates no duplicates." },
      { q: "What does anti-raid do to my server?", a: "It counts how many new members arrive within a short time (through Discord's own join notice). Past the limit you set it raises the alarm and, depending on your setting, only alerts, raises the verification level one step or locks the chat channels. Everything it changes is recorded and put back exactly as it was when time is up or when you press Unlock. A channel someone edited by hand during the lock is left alone." },
      { q: "Does the anti-nuke guard ban people on its own?", a: "No. When one person deletes several channels or roles in a row it raises the alarm and takes that person's dangerous roles away (it needs the View Audit Log permission). The owner, the bot and anyone at or above the bot's role are never touched. It is a Pro feature." },
      { q: "How much does it cost per month?", a: "Pro is $3.99 and Plus $7.99 per server per 30 days. A year costs ten months. There is also a one-off Build it for me at $4.99 that gives 7 days of Pro. The free plan still has the guided setup, anti-raid, the mod log and the moderation commands, and builds twice." },
      { q: "What permissions does it need?", a: "Whoever runs the command needs Administrator. The bot needs Manage Channels, Manage Roles and Manage Server, and must be able to post in the read-only channels it creates. The easy way is to invite it with Administrator." },
      { q: "Will it delete my existing channels?", a: "No. /build and /batdau only add, and channels with the same name are skipped. /nuke only removes what the bot itself created, by the IDs it recorded." },
      { q: "Does running /build twice create duplicates?", a: "No. What exists is skipped, and content like rules and the welcome is not posted again. The free plan allows two builds, and running exactly the setup that was already built costs none." },
      { q: "Does the AI build straight into my server?", a: "Never. Its answer is cleaned (mentions and blocked words removed, counts capped) and shown as a blueprint for you to review and edit. Nothing is created until you press build. The /vietgiup helper only writes drafts, it never posts by itself." },
      { q: "Where does my group description go?", a: "The description you type into /thietke or /vietgiup is sent to Google Gemini to create the design or the draft, with no usernames or messages. The bot uses Google's free tier, so Google may use it to improve its products. Do not put anything private in it." },
      { q: "What does the bot store about my server?", a: "The IDs of the channels and roles it created, each tool's settings, the active plan and usage counts. When you switch the newer features on it also keeps activity points by member ID, moderation cases, giveaway entries, poll votes, role menus, temporary room records, scheduled messages, personal reminders and suggestions with their votes. See the privacy page for the full list. It does not read message content. Run /xoadulieu so it forgets what it built and its settings." },
      { q: "Does a custom blocked word list mean the bot reads messages?", a: "No. The contractor only writes the word list into Discord's native keyword rule. Discord blocks the message before anyone sees it, and the bot never receives it. The words you type are stored in your server's settings." },
      { q: "Can temporary voice rooms delete my own channels?", a: "No. Every room the contractor makes is recorded, and it only deletes rooms in that record, once they are empty. Channels you made yourself, even ones with a similar name, are never touched." },
      { q: "Can a scheduled message ping the whole server?", a: "No. Scheduled messages never ping anyone, even if the text contains @everyone or a role name. To call the whole group, post by hand." },
      { q: "Why does the music not come automatically?", a: "Because Discord forbids bots from inviting bots. The contractor puts the invite button in the DJ channel and you click it once." },
    ],
  },
  cta: {
    title: "Your server has waited long enough.",
    label: "Start",
    steps: ["Invite the contractor to your server (Administrator is easiest)", "Press the Start button the bot posts, or run /batdau, and pick a few options", "Press Build and go make coffee. Want to edit the blueprint yourself? Use /build or /thietke"],
    button: "Invite the contractor",
    setupId: "setup",
  },
  themePage: {
    open: "See the full channel tree",
    back: "All themes",
    label: "Blueprint",
    ownRoles: "Roles this theme adds",
    sharedRoles: "Roles every server gets",
    tree: "Channel tree",
    treeLede: "This is the real channel tree the bot builds when you pick this theme alone. Channel names are always in Vietnamese.",
    voice: "voice room",
    staffOnly: "mods only",
    counts: "{categories} categories, {channels} channels, {roles} roles, {rules} rules",
    invite: "Invite the contractor to build this",
    inviteHint: "Invite the bot, then run /batdau or /build and pick this theme.",
    cmdLabel: "Command to build it",
    prev: "Previous theme",
    next: "Next theme",
    mix: "Mix in other themes on the drafting table on the home page (Pro plan).",
    seeAll: "See all eleven themes",
    metaTitle: "{label}, a Thau Xay Dung Discord theme",
  },
  status: {
    title: "Is the contractor at work?",
    label: "Status",
    sub: "This page asks the bot directly from your browser. If the bot does not answer, the page only says it cannot check, which does not mean the bot is broken.",
    checking: "Checking...",
    ok: "At work",
    slow: "The bot answered but its heartbeat is old, it may have just restarted",
    unknown: "cannot check",
    unknownHint: "Your browser could not reach the bot just now. Try again in a few minutes.",
    fields: { version: "Version", uptime: "Running for", servers: "Servers", heartbeat: "Last heartbeat" },
    servers: "about {n}",
    ago: "{n} seconds ago",
    uptime: { d: "d", h: "h", m: "min", s: "s" },
    retry: "Check again",
    note: "The server count is rounded down to ten. The page stores nothing and shows no server ID or name.",
    back: "Back to home",
  },
  footer: {
    word: "BUILT IT",
    privacy: "Privacy",
    terms: "Terms",
    devlog: "Engineering devlog",
    source: "Source code",
    line: "A personal project, not affiliated with Discord. Ridiculous construction, no warranty.",
    block: { project: "Project", drawn: "Drawn by", stack: "Stack", sheet: "Sheet", links: "Links" },
  },
};

export default en;
