import type { Dict } from "./types";

const en: Dict = {
  lang: "en",
  meta: {
    title: "Thau Xay Dung, the Discord bot that builds a whole server in one command",
    description:
      "Invite the bot to an empty server, run /build or describe your group to an AI, review the blueprint, edit it, then build. Channels, roles, rules and a welcome, all of it ridiculous. Channel names stay in Vietnamese.",
  },
  nav: {
    how: "How it builds",
    themes: "Blueprints",
    pricing: "Plans",
    commands: "Commands",
    faq: "FAQ",
    devlog: "Devlog",
    cta: "Invite the contractor",
    switchTo: "VI",
    switchHref: "/",
    theme: "Toggle light and dark theme",
    home: "Back to top",
  },
  hero: {
    title: "Your server is as empty as a wallet at month's end.",
    sub: "Invite the contractor and run /build, or describe your group to an AI. A few minutes later your server has channels, roles, rules and some loving insults. Not inspected yet, but go ahead and use it.",
    cta: "Invite the contractor",
    secondary: "Watch the construction",
    dim: "1 command, a few minutes",
  },
  plotter: {
    title: "Drafting table",
    chipsLabel: "Pick themes, mix as many as you like",
    hint: "Press to add or drop a theme. The tree below is the bot's real output for each mix.",
    proNote: "Mixing themes is a Pro feature. Channels with the same name appear once.",
    limit: "At most 4 themes at once, like the /build command.",
    categories: "categories",
    channels: "channels",
    roles: "roles",
    rules: "rules",
    build: "Try a build",
    done: "Signed off",
    summary: "{categories} categories, {channels} channels, {roles} roles",
  },
  scene: {
    title: "From bare ground to a finished server.",
    label: "How it builds",
    steps: [
      { t: "Call the contractor", d: "An admin runs /build and picks one or more themes. The bot posts a blueprint for approval first and touches nothing yet." },
      { t: "Pour the role foundation", d: "A Chairman, Mods, a Slave Bot and a few self-assign roles, each with a name nobody will admit to choosing." },
      { t: "Raise the channels", d: "Categories, text channels, voice rooms, and mod-only channels only mods can see. Announcement and rules channels are locked to read-only." },
      { t: "Post the rules", d: "Rules, a welcome and a role-picker with buttons land in the right channels. The DJ and text-to-speech rooms come with invite buttons." },
      { t: "Sign-off", d: "Done. Running /build again creates no duplicates, and /nuke removes exactly what the bot built." },
    ],
    cmd: "/build theme: Game Thủ Cày Đêm",
    roles: "Roles",
    rules: "Server rules",
    stamp: "Signed off",
  },
  ai: {
    title: "Describe your group, an AI builds your server.",
    label: "AI designer",
    sub: "Not into the built-in themes? Tell the contractor who your group is and what it likes. Google Gemini comes up with categories, channels, roles, rules and a welcome that fit, then you review and edit it before anything is built. Switch the humor level below to see three real answers.",
    inputLabel: "You type",
    description: "Group of 8 college friends, play Valorant on Saturday nights and chat a lot",
    levelLabel: "Humor level",
    levels: ["Gentle", "Troll", "Absurd"],
    resultLabel: "The AI returns",
    provenance: "All three are real answers, run on {date} with {model}. Every run gives a different result. The AI writes in Vietnamese.",
    plan: "Available from the Pro plan. Each server has a monthly number of AI designs.",
  },
  editor: {
    title: "Review, edit, then build.",
    label: "Blueprint",
    sub: "Both /build and /thietke show you the whole channel tree before anything is created. Next to this text is a working miniature that follows the bot's own rules: drop a category, rename one, add a channel, then press build.",
    points: [
      { t: "Remove a category", d: "Do not need a section? Drop it from the blueprint. The admin area stays, because the rules and welcome live there." },
      { t: "Rename", d: "Press a category name to rename it to your group's voice. Names cannot collide." },
      { t: "Add a channel", d: "Add a text channel or voice room of your own. A channel with an existing name is refused." },
      { t: "Confirm", d: "Only the person who ran the command, and only an administrator, can press build. A blueprint expires after 15 minutes." },
    ],
    tryLabel: "Try it right here",
    locked: "fixed",
    remove: "Drop",
    rename: "Rename category",
    renameHint: "Press to rename",
    addPlaceholder: "new channel name",
    text: "text",
    voice: "voice",
    add: "Add channel",
    build: "Build it, boss",
    reset: "Reset blueprint",
    counts: "{c} categories, {ch} channels",
    removed: "Dropped {name}.",
    renamed: "Category renamed.",
    added: "Added channel {name}.",
    duplicate: "That name already exists, left as it was.",
    building: "Building...",
    done: "Done, signed off.",
  },
  themes: {
    title: "Eleven built-in blueprints.",
    label: "Themes",
    sub: "The shared part (admin area, DJ rooms, mod backstage) comes with every theme. Each theme adds its own categories, channels, roles and two rules.",
    items: [
      { id: "gaming", label: "Late-Night Gamers", blurb: "For gaming crews: a team finder, a clip showcase and a place to cry after a loss." },
      { id: "hoc-tap", label: "Studying Without Studying", blurb: "For study groups: homework help, burning deadlines, an exam-eve room." },
      { id: "cong-dong", label: "General Store Community", blurb: "For any community: chatter, photo sharing, events and assorted odds and ends." },
      { id: "chill-ban-be", label: "Chill With the Crew", blurb: "For close friends: an archive of each other's bad photos and plans nobody follows." },
      { id: "booking", label: "Book a Friend", blurb: "For servers where people book a friend to play or talk: booking guide, price list, player profiles, feedback and scam protection." },
      { id: "anime", label: "Anime Fan Club", blurb: "For anime and manga fans: recommendations, reviews, spoilers behind a fence, fanart and waifu wars." },
      { id: "dev-code", label: "Wandering Coders", blurb: "For programmers: bug help, project showcase, code review, jobs and mourning the Friday afternoon deploy." },
      { id: "creator", label: "Creator Studio", blurb: "For streamers, YouTubers and TikTokers: ideas, video feedback, live schedule, collabs and honest numbers." },
      { id: "phim-nhac", label: "Cinema and Music Room", blurb: "For movie and music lovers: suggestions, votes for movie night, shared playlists and karaoke." },
      { id: "cong-so", label: "One-House Office", blurb: "For a company team or project group: announcements, today's tasks, deadlines and lunch-break chatter." },
      { id: "thu-cung", label: "Pet Lovers Club", blurb: "For people with dogs and cats: show off the boss, ask for care tips, find homes and share the household stories." },
    ],
    rolesLabel: "Own roles",
    sharedLabel: "Shared",
    mixNote: "Studying, gaming and chilling all at once? The Pro plan mixes up to 4 themes in one server. Try it on the drafting table above.",
  },
  rules: {
    title: "Rules nobody reads, but everyone gets reminded of.",
    label: "Rules",
    sub: "Eight shared rules plus two per theme, posted into the rules channel. A few samples (in Vietnamese, as the bot writes them):",
  },
  music: {
    title: "What about music and text-to-speech?",
    label: "Music and TTS",
    body: "Discord does not let a bot invite another bot, only a person can. So the contractor does what it can: it builds the DJ room, the karaoke room and the text-to-speech room, and puts an invite button for a music bot and a TTS bot right in the channel. An admin clicks once and the music starts.",
    points: ["#dj-booth has a music bot invite button", "#chém-gió-bằng-giọng has a TTS bot invite button", "You configure the bot links, the contractor just places the buttons"],
  },
  pricing: {
    title: "Three plans, paid per server.",
    label: "Plans",
    sub: "One plan per server. Buy an activation code, run /kichhoat, use it right away. When it ends the server returns to the free plan and what was already built stays.",
    plans: [
      {
        id: "free",
        name: "Free",
        price: "$0",
        blurb: "To see how the contractor works.",
        features: ["1 built-in theme", "1 build", "Review and edit the blueprint", "/nuke to clean up", "No AI"],
      },
      {
        id: "pro",
        name: "Pro",
        price: "$9.99 / 30 days",
        blurb: "For groups that want a server that fits them.",
        features: ["Mix up to 4 themes", "Unlimited builds", "AI design: 20 per month", "Pick the humor level", "Review and edit the blueprint"],
      },
      {
        id: "plus",
        name: "Plus",
        price: "$19.99 / 30 days",
        blurb: "For people who build many servers.",
        features: ["Everything in Pro", "AI design: 100 per month"],
      },
    ],
    howTitle: "How to buy",
    how: ["Message the bot owner on Instagram with the plan and number of days you want", "Pay as instructed and receive a code like THAU-XXXX-XXXX-XXXX", "Run /kichhoat ma:<code> in your server. A code works once, and a second code of the same plan adds its days"],
    contact: "Message on Instagram to buy a code",
    note: "Prices are in US dollars, per server, per 30 days. Customers in Vietnam pay the VND equivalent at the exchange rate on the day. Want more days? Message to work it out. There are no automatic payments yet.",
  },
  commands: {
    title: "Seven commands for customers, no more.",
    label: "Commands",
    hint: "press to copy",
    copied: "copied",
    items: [
      { name: "/build", args: "theme theme2 theme3 theme4", d: "Builds the server from one or more themes. Shows an editable blueprint and asks for confirmation. Admins only." },
      { name: "/thietke", args: "mota muc-do-hai", d: "An AI designs your own server from a description. From the Pro plan, with a monthly allowance." },
      { name: "/nuke", args: "", d: "Tears down what the bot built. Only touches channels and roles the bot created, with a confirm button." },
      { name: "/kichhoat", args: "ma", d: "Activates a paid plan for the server with a code you bought." },
      { name: "/goi", args: "", d: "Shows the current plan, how many builds were used and how to upgrade." },
      { name: "/xoadulieu", args: "", d: "The bot forgets the list of channels and roles it built. The channels and roles on Discord stay." },
      { name: "/roast", args: "nguoi", d: "Gently roasts a member for fun. Cannot mod, cannot mute, can only offend." },
    ],
  },
  faq: {
    title: "FAQ",
    label: "FAQ",
    items: [
      { q: "What permissions does it need?", a: "Whoever runs the command needs Administrator. The bot needs Manage Channels, Manage Roles and Manage Server, and must be able to post in the read-only channels it creates. The easy way is to invite it with Administrator." },
      { q: "Will it delete my existing channels?", a: "No. /build only adds, and channels with the same name are skipped. /nuke only removes what the bot itself created, by the IDs it recorded." },
      { q: "Does running /build twice create duplicates?", a: "No. What exists is skipped, and content like rules and the welcome is not posted again. The free plan allows one build, though." },
      { q: "Does the AI build straight into my server?", a: "Never. Its answer is cleaned (mentions and blocked words removed, counts capped) and shown as a blueprint for you to review and edit. Nothing is created until you press build." },
      { q: "Where does my group description go?", a: "The description you type is sent to Google Gemini to create the design, with no usernames or messages. The bot uses Google's free tier, so Google may use it to improve its products. Do not put anything private in it." },
      { q: "What does the bot store about my server?", a: "The IDs of the channels and roles it created, the active plan and usage counts for some features. It does not read message content. Run /xoadulieu so it forgets what it built." },
      { q: "Why does the music not come automatically?", a: "Because Discord forbids bots from inviting bots. The contractor puts the invite button in the DJ channel and you click it once." },
    ],
  },
  cta: {
    title: "Your server has waited long enough.",
    label: "Start",
    steps: ["Invite the contractor to your server (Administrator is easiest)", "Run /build or /thietke, review the blueprint, edit if you like", "Hit build and go make coffee"],
    button: "Invite the contractor",
    setupId: "setup",
  },
  footer: {
    word: "BUILT IT",
    privacy: "Privacy",
    terms: "Terms",
    devlog: "Engineering devlog",
    source: "Source code",
    line: "A personal project, not affiliated with Discord. Ridiculous construction, no warranty.",
    block: { project: "Project", drawn: "Drawn by", stack: "Stack", sheet: "Sheet", links: "Links" },
  },
};

export default en;
