export type Doc = { title: string; updated: string; back: string; sections: { h: string; p: string[] }[] };
type Pair = { vi: Doc; en: Doc };

const updated = { vi: "Cập nhật lần cuối: 03/10/2026", en: "Last updated: 3 October 2026" };

export const privacy: Pair = {
  vi: {
    title: "Quyền riêng tư",
    updated: updated.vi,
    back: "Về trang chủ",
    sections: [
      { h: "Bot lưu gì", p: ["Với mỗi server, bot lưu ID server, tên theme đã dùng, ID của các kênh, danh mục và role mà bot đã tạo, giấy phép đang dùng (gói, ngày hết hạn) và số lần dùng một số tính năng để tính hạn mức gói.", "Khi bạn dùng các tính năng khác, bot còn lưu: theme riêng đã lưu, bản sao lưu cấu trúc server (tên và quyền của role, kênh, danh mục, không có nội dung tin nhắn), lịch sự kiện định kỳ, và điểm, chuỗi điểm danh cùng ngày điểm danh gần nhất của từng thành viên theo ID Discord. Khi mua gói bằng /mua, bot lưu đơn hàng gồm gói, số ngày, số tiền, trạng thái và ID Discord của server và người gõ lệnh."] },
      { h: "Công cụ quản trị và bảng điều khiển", p: ["Khi bạn dùng chào người mới, AutoMod và ticket, bot lưu cài đặt của từng công cụ (ID kênh và role bạn chọn, lời chào bạn viết), ID kênh ticket cùng ID người mở và người đóng, thời điểm mở và đóng, và các điểm sức khoẻ server của những lần khám gần đây. Bot không lưu nội dung ticket hay tin nhắn nào. Luật AutoMod do chính Discord thực thi.", "Nếu bạn đăng nhập bảng điều khiển trên web, bot dùng đăng nhập Discord để biết bạn là ai và bạn quản trị những server nào, rồi thu hồi ngay mã truy cập đó. Bot chỉ giữ một cookie phiên có chữ ký trong trình duyệt của bạn, không lưu mật khẩu hay mã truy cập của bạn."] },
      { h: "Bảo vệ, quản trị và nhật ký", p: ["Khi bạn dùng chống raid, khoá khẩn cấp và chống xoá hàng loạt, bot lưu cài đặt (ngưỡng, hành động, kênh báo động) và trạng thái khoá đang chạy: danh sách kênh bị khoá cùng quyền gửi tin trước đó của @everyone và mức xác minh cũ, để trả lại đúng như cũ. Số lần người vào hoặc xoá kênh được đếm trong bộ nhớ, không lưu lại.", "Khi bạn dùng /canhcao, /timeout, /kick và /ban, bot lưu một hồ sơ cho mỗi lần xử lý: ID người bị xử, ID người xử, loại việc, lý do do người xử gõ (tối đa 300 ký tự), thời điểm và thời hạn timeout. Admin xem lại bằng /hoso. Nhật ký quản trị ghi vào kênh bạn chọn ai bị cấm hoặc gỡ cấm, role nào đổi quyền, và luật AutoMod nào chặn ai ở kênh nào. Nhật ký không ghi nội dung tin bị chặn."] },
      { h: "Điểm hoạt động, giveaway, bình chọn, menu role", p: ["Khi bật điểm hoạt động, bot lưu cho mỗi thành viên (theo ID Discord): điểm, số tin nhắn đã tính, số phút ở kênh thoại, và điểm đã nhận trong ngày. Bot chỉ biết ai nhắn ở kênh nào và ai ở kênh thoại nào, không đọc và không lưu chữ nào.", "Giveaway lưu ID những người bấm Tham gia và người trúng. Bình chọn lưu ID người bầu và lựa chọn của họ để mỗi người chỉ bầu một lần; tin bình chọn không hiện ai bầu gì. Menu role lưu những role mà menu cho nhận, không lưu ai đã nhận role nào."] },
      { h: "Phòng thoại tạm, kênh thống kê, tin hẹn giờ, nhắc việc, góp ý, từ khoá chặn", p: ["Phòng thoại tạm: bot lưu ID kênh của mỗi phòng nó tạo, ID người tạo và thời điểm tạo, cho tới khi phòng bị xoá. Kênh thống kê chỉ lưu cài đặt (ID kênh, loại số, mẫu tên) và không lưu gì về thành viên. Tin nhắn hẹn giờ lưu kênh, nội dung quản trị viên viết, giờ đăng và ID người tạo. Danh sách từ khoá chặn riêng do quản trị viên gõ được lưu trong cài đặt AutoMod của server, và bot không bao giờ nhận hay lưu tin nhắn bị chặn vì Discord tự chặn.", "Nhắc việc (/nhacviec): bot lưu ID của người đặt, nội dung họ gõ (tối đa 300 ký tự), giờ nhắc, và server cùng kênh nơi họ đặt (để nhắc ở kênh khi không nhắn riêng được). Lời nhắc đã gửi xong bị xoá sau một tháng và mọi lời nhắc bị xoá sau tối đa một năm; người dùng tự xoá được bằng /nhacviec xoa. Góp ý (/gopy): bot lưu ID người gửi, nội dung họ gõ (tối đa 500 ký tự), quyết định của quản lý kèm ghi chú, và mỗi phiếu vote theo ID thành viên (lên hoặc xuống); tin góp ý không hiện ai bầu gì. Lọc tài khoản mới chỉ đọc ngày tạo tài khoản của người vào và không lưu gì."] },
      { h: "Số liệu ẩn danh", p: ["Để biết người dùng rớt ở bước nào, bot đếm từng bước một: mời bot, chạy xong /batdau, dựng xong, dùng thử, trả tiền, rời đi. Mỗi lần đếm chỉ lưu ID server, tên bước và thời điểm, không có tên hay ID người dùng và không có nội dung. Bản tin tuần dùng cùng cách đếm cho số người mới vào và số tin bị AutoMod chặn."] },
      { h: "Trang trạng thái", p: ["Trang trạng thái của website hỏi thẳng bot ngay trong trình duyệt của bạn. Bot trả về phiên bản, thời gian đã chạy, số server (làm tròn xuống chục) và độ mới của nhịp tim, không có ID hay tên nào. Website không lưu kết quả đó."] },
      { h: "Thiết kế bằng AI", p: ["Khi bạn dùng /thietke hoặc /vietgiup, đoạn mô tả bạn gõ được gửi tới dịch vụ Gemini của Google để tạo bản thiết kế hoặc bản nháp. Với giải thích kết quả khám sức khoẻ, các phát hiện của chính bot (không có nội dung tin nhắn) được gửi kèm. Chỉ có vậy được gửi, không kèm tên người dùng hay nội dung tin nhắn. Bot đang dùng gói miễn phí của Google, nên Google có thể dùng nội dung gửi qua gói này để cải thiện sản phẩm của họ. Đừng nhập thông tin cá nhân hay bí mật vào phần mô tả."] },
      { h: "Thanh toán", p: ["Thanh toán tự động đi qua Stripe (stripe.com, bằng thẻ) hoặc payOS (payos.vn, bằng QR ngân hàng Việt Nam). Bạn nhập thông tin thẻ hoặc ngân hàng trên trang của Stripe, payOS và ngân hàng, không bao giờ trên Discord hay trên bot. Bot không thấy và không lưu số tài khoản hay thẻ của bạn, chỉ biết đơn đã thanh toán hay chưa."] },
      { h: "Bot không làm gì", p: ["Bot không đọc, không lưu nội dung tin nhắn, không yêu cầu quyền Message Content và không dùng intent đặc quyền nào của Discord. Bot chỉ nhận các sự kiện: tin nhắn (để biết ai nhắn ở đâu và để thấy thông báo tham gia của Discord, không để đọc chữ), trạng thái kênh thoại (để tạo và dọn phòng tạm và tính điểm thoại), cấm và gỡ cấm, và AutoMod chặn tin. Bot không bán hay chia sẻ dữ liệu cho bên thứ ba."] },
      { h: "Quyền hạn trên server", p: ["Bot cần quyền quản lý kênh, role và server để dựng server. Bot chỉ xoá những kênh và role chính nó đã tạo, và chỉ khi quản trị viên bấm xác nhận."] },
      { h: "Xoá dữ liệu", p: ["Quản trị viên gõ /xoadulieu để bot quên danh sách kênh và role đã xây cùng các cài đặt. Giấy phép, số lần dùng và dấu đã dùng thử vẫn được giữ để tính gói. Lệnh này cũng xoá điểm hoạt động, hồ sơ xử lý, người tham gia giveaway, phiếu bình chọn, menu role, ticket, backup, theme riêng, danh sách từ khoá chặn riêng, bản ghi phòng thoại tạm, tin nhắn hẹn giờ, lời nhắc đặt trong server đó và góp ý cùng phiếu vote của server. Muốn xoá dữ liệu của riêng một thành viên, hãy nhắn chủ bot. Đuổi bot khỏi server cũng ngừng mọi hoạt động của bot ở đó."] },
      { h: "Liên hệ", p: ["Có câu hỏi về dữ liệu, hãy nhắn chủ bot trên Instagram: instagram.com/nhaajt_hehee, hoặc xem nhaajt.com."] },
    ],
  },
  en: {
    title: "Privacy",
    updated: updated.en,
    back: "Back to home",
    sections: [
      { h: "What the bot stores", p: ["For each server the bot stores the server ID, the theme used, the IDs of the channels, categories and roles it created, the active license (plan and expiry date) and how many times some features were used, to apply plan limits.", "When you use the other features the bot also stores: saved themes, backups of the server layout (names and permissions of roles, channels and categories, never message content), recurring event schedules, and each member's points, check-in streak and last check-in day, by Discord ID. When you buy a plan with /mua the bot stores the order: the plan, days, amount, status and the Discord IDs of the server and the person who ran the command."] },
      { h: "Admin tools and the dashboard", p: ["When you use the welcome flow, AutoMod and tickets, the bot stores each tool's settings (the channel and role IDs you pick, the welcome text you write), the ID of each ticket channel with the IDs of who opened and closed it and when, and the health scores of recent checks. It stores no ticket content and no messages. AutoMod rules are enforced by Discord itself.", "If you sign in to the web dashboard, the bot uses Discord sign-in to learn who you are and which servers you administer, then revokes that access token straight away. It keeps only a signed session cookie in your browser, never your password or your access token."] },
      { h: "Protection, moderation and the log", p: ["When you use anti-raid, lockdown and the anti-nuke guard, the bot stores the settings (thresholds, action, alert channel) and the state of a running lockdown: the list of locked channels with @everyone's previous send permission and the old verification level, so it can put things back exactly. Counts of joins or deletions are held in memory and not stored.", "When you use /canhcao, /timeout, /kick and /ban the bot stores one case per action: the ID of the member, the ID of the moderator, the kind of action, the reason the moderator typed (up to 300 characters), the time and the length of a timeout. Admins read them back with /hoso. The mod log writes to the channel you pick who was banned or unbanned, which role changed permissions, and which AutoMod rule blocked whom in which channel. The log never includes the text of a blocked message."] },
      { h: "Activity points, giveaways, polls, role menus", p: ["When activity points are on, the bot stores per member (by Discord ID): points, the number of messages counted, minutes in voice rooms, and points earned today. It only knows who wrote in which channel and who is in which voice room, and never reads or stores any text.", "Giveaways store the IDs of people who pressed Join and of the winners. Polls store the ID of each voter and their choice so everyone votes once; the poll message never shows who voted for what. Role menus store which roles a menu offers, not who took which role."] },
      { h: "Temporary rooms, stats channels, scheduled messages, reminders, suggestions, blocked words", p: ["Temporary voice rooms: the bot stores the channel ID of each room it makes, the ID of the member who made it and the time, until the room is deleted. Stats channels store only settings (the channel ID, the kind of number, the name template) and nothing about members. Scheduled messages store the channel, the text an administrator wrote, the time and the ID of whoever created it. The custom blocked word list an administrator types is stored in the server's AutoMod settings, and the bot never receives or stores a blocked message because Discord does the blocking.", "Reminders (/nhacviec): the bot stores the ID of the person, the text they typed (up to 300 characters), the due time, and the server and channel where it was made (to remind in the channel when direct messages fail). A delivered reminder is deleted after a month and every reminder after a year at most; people can delete their own with /nhacviec xoa. Suggestions (/gopy): the bot stores the ID of the sender, the text they typed (up to 500 characters), the staff decision with its note, and each vote by member ID (up or down); the suggestion message never shows who voted. The new-account filter only reads the creation date of the account that joins and stores nothing."] },
      { h: "Anonymous counts", p: ["To learn where people drop off, the bot counts each step: invited, finished /batdau, built, tried, paid, left. Each count stores only the server ID, the name of the step and the time, with no user name or ID and no content. The weekly report uses the same counting for new members and AutoMod blocks."] },
      { h: "The status page", p: ["The website's status page asks the bot directly from your browser. The bot answers with its version, how long it has run, a server count (rounded down to ten) and how fresh its heartbeat is, with no ID or name. The website does not store that answer."] },
      { h: "AI design", p: ["When you use /thietke or /vietgiup, the description you type is sent to Google's Gemini service to create the design or the draft. For the plain-words explanation of a health check, the bot's own findings (never message content) are sent with it. Only that is sent, with no usernames or message content. The bot currently uses Google's free tier, so Google may use content sent through it to improve its products. Do not enter personal or secret information in the description."] },
      { h: "Payments", p: ["Automatic payments go through Stripe (stripe.com, by card) or payOS (payos.vn, by Vietnamese bank QR code). You enter your card or bank details on the pages of Stripe, payOS and your bank, never on Discord or in the bot. The bot does not see or store your account or card number, only whether the order has been paid."] },
      { h: "What the bot does not do", p: ["The bot does not read or store message content, does not ask for the Message Content permission and uses no privileged Discord intent. It only receives these events: messages (to know who wrote where and to see Discord's join notice, not to read text), voice room state (to make and clean up temporary rooms and to count voice points), bans and unbans, and AutoMod blocks. It does not sell or share data with third parties."] },
      { h: "Permissions on your server", p: ["The bot needs permission to manage channels, roles and the server in order to build it. It only deletes channels and roles it created itself, and only after an administrator confirms."] },
      { h: "Deleting data", p: ["An administrator can run /xoadulieu so the bot forgets the list of channels and roles it built and the settings. The license, usage counts and the trial mark are kept to apply the plan. The command also removes activity points, moderation cases, giveaway entries, poll votes, role menus, tickets, backups, saved themes, the custom blocked word list, temporary room records, scheduled messages, reminders made in that server, and suggestions with their votes for the server. To have one member's data deleted, message the bot owner. Removing the bot from the server stops all bot activity there."] },
      { h: "Contact", p: ["For questions about data, message the bot owner on Instagram: instagram.com/nhaajt_hehee, or see nhaajt.com."] },
    ],
  },
};

export const terms: Pair = {
  vi: {
    title: "Điều khoản sử dụng",
    updated: updated.vi,
    back: "Về trang chủ",
    sections: [
      { h: "Dịch vụ", p: ["Thầu Xây Dựng là bot Discord dựng kênh, role, luật và nội dung cho server. Đây là dự án cá nhân, không liên kết với Discord Inc."] },
      { h: "Gói và mã kích hoạt", p: ["Gói miễn phí có giới hạn về số lần xây và số theme. Gói trả phí được mở bằng lệnh /mua (tự bật khi thanh toán thành công) hoặc bằng mã kích hoạt dùng một lần, gắn với một server và có hạn dùng. Hết hạn thì server tự về gói miễn phí, những gì đã xây vẫn ở lại. Giá tính theo server; mua một năm trả mười tháng. Gói Dựng giúp là mua một lần và cấp 7 ngày Pro, không tự gia hạn. Mỗi server được dùng thử Pro 7 ngày một lần. Bot nhắc trước khi gói hết hạn một lần trước 3 ngày và một lần khi hết, và có thể thay đổi giá cho lần mua sau mà không ảnh hưởng gói đã mua."] },
      { h: "Thanh toán và hoàn tiền", p: ["Gói mua bằng /mua và mã kích hoạt bán thủ công qua tin nhắn đều theo quy tắc sau. Gói hoặc mã chưa dùng có thể được hoàn tiền nếu bạn yêu cầu trong vòng 7 ngày kể từ khi mua. Gói hoặc mã đã kích hoạt không được hoàn tiền, trừ khi bot không dùng được vì lỗi của chủ bot trong thời gian dài, khi đó thời hạn sẽ được bù thêm ngày."] },
      { h: "Trách nhiệm của quản trị viên", p: ["Bạn chịu trách nhiệm cho server của mình, kể cả nội dung bạn chỉnh sửa hoặc nhập vào bot. Không dùng bot để vi phạm Điều khoản của Discord hoặc pháp luật."] },
      { h: "Lệnh xử lý thành viên", p: ["Cảnh cáo, timeout, kick, ban là quyết định của người gõ lệnh, không phải của bot. Người gõ lệnh chịu trách nhiệm về lý do và về việc xử đúng người, và chủ server chịu trách nhiệm về việc cấp quyền cho nhân viên. Bot lưu hồ sơ và gửi tin nhắn riêng cho người bị xử, và từ chối khi vai vế không cho phép, nhưng không kiểm tra lý do đúng hay sai. Hồ sơ là dữ liệu của server bạn, hãy dùng đúng mục đích quản trị và giữ kín với người ngoài."] },
      { h: "Chống raid và chống xoá hàng loạt", p: ["Các tính năng bảo vệ làm hết sức nhưng không bảo đảm chặn được mọi cuộc tấn công, có thể báo nhầm, và phụ thuộc vào việc bot có đủ quyền và vị trí role. Khi khoá khẩn cấp, bot ghi lại những gì nó đổi và trả về đúng như cũ, nhưng không đụng vào chỗ đã bị ai chỉnh tay. Bạn nên kiểm tra server sau mỗi lần khoá."] },
      { h: "Giveaway và bình chọn", p: ["Người mở giveaway chịu trách nhiệm về phần thưởng, về việc trao thưởng và về việc tuân thủ luật địa phương và quy định của Discord về giveaway. Bot chỉ bốc thăm ngẫu nhiên giữa những người đã bấm Tham gia. Bình chọn chỉ mang tính tham khảo trong nhóm của bạn."] },
      { h: "Không bảo đảm", p: ["Bot được cung cấp theo hiện trạng. Có thể gián đoạn hoặc lỗi, và nội dung hài hước có thể không hợp với mọi cộng đồng; hãy xem bản vẽ trước khi xác nhận. Chủ bot có quyền từ chối hoặc ngừng phục vụ khi có lạm dụng."] },
      { h: "Thay đổi", p: ["Điều khoản có thể được cập nhật; ngày cập nhật nằm ở đầu trang."] },
    ],
  },
  en: {
    title: "Terms of use",
    updated: updated.en,
    back: "Back to home",
    sections: [
      { h: "The service", p: ["Thau Xay Dung is a Discord bot that builds channels, roles, rules and content for a server. It is a personal project and is not affiliated with Discord Inc."] },
      { h: "Plans and activation codes", p: ["The free plan limits the number of builds and themes. Paid plans are unlocked with the /mua command (the plan switches on when the payment succeeds) or with a one-time activation code tied to one server and valid for a set period. When it ends the server returns to the free plan and what was already built stays. Prices are per server; a year costs ten months. Build it for me is a one-off purchase that grants 7 days of Pro and does not renew. Each server may try Pro free for 7 days once. The bot reminds you once three days before a plan ends and once when it ends, and prices may change for later purchases without affecting a plan already bought."] },
      { h: "Payment and refunds", p: ["Plans bought with /mua and activation codes sold by hand through messages follow the same rule. An unused plan or code can be refunded if you ask within 7 days of buying it. A plan or code that has been activated is not refunded, unless the bot was unusable for a long time because of the owner, in which case extra days are added."] },
      { h: "Administrator responsibility", p: ["You are responsible for your server, including any content you edit or enter into the bot. Do not use the bot to break Discord's terms or the law."] },
      { h: "Moderation commands", p: ["Warning, timing out, kicking and banning are decisions of the person who runs the command, not of the bot. That person is responsible for the reason and for acting on the right member, and the server owner is responsible for who is given the permissions. The bot stores the case and sends the member a private message, and refuses when the role order does not allow it, but it does not judge whether a reason is fair. Case files are your server's data: use them for moderation only and keep them from outsiders."] },
      { h: "Anti-raid and anti-nuke", p: ["The protection features do their best but cannot promise to stop every attack, can raise false alarms, and depend on the bot having the permissions and role position it needs. During a lockdown the bot records what it changes and puts it back as it was, but does not touch anything someone edited by hand. Check your server after every lockdown."] },
      { h: "Giveaways and polls", p: ["Whoever opens a giveaway is responsible for the prize, for handing it over, and for following local law and Discord's rules about giveaways. The bot only draws at random among people who pressed Join. Polls are informal and for your own group."] },
      { h: "No warranty", p: ["The bot is provided as is. It may be interrupted or have errors, and its humor may not suit every community; review the blueprint before confirming. The bot owner may refuse or stop service in case of abuse."] },
      { h: "Changes", p: ["These terms may be updated; the date is at the top of the page."] },
    ],
  },
};
