export type PlanCopy = { id: string; name: string; price: string; blurb: string; features: string[] };

export type Dict = {
  lang: "vi" | "en";
  meta: { title: string; description: string };
  nav: {
    how: string;
    themes: string;
    pricing: string;
    commands: string;
    faq: string;
    devlog: string;
    cta: string;
    switchTo: string;
    switchHref: string;
    theme: string;
    home: string;
  };
  hero: { title: string; sub: string; cta: string; secondary: string; dim: string };
  plotter: {
    title: string;
    chipsLabel: string;
    hint: string;
    proNote: string;
    limit: string;
    categories: string;
    channels: string;
    roles: string;
    rules: string;
    build: string;
    done: string;
    summary: string;
  };
  scene: {
    title: string;
    label: string;
    steps: { t: string; d: string }[];
    cmd: string;
    roles: string;
    rules: string;
    stamp: string;
  };
  ai: {
    title: string;
    label: string;
    sub: string;
    inputLabel: string;
    description: string;
    levelLabel: string;
    levels: string[];
    resultLabel: string;
    provenance: string;
    plan: string;
  };
  editor: {
    title: string;
    label: string;
    sub: string;
    points: { t: string; d: string }[];
    tryLabel: string;
    locked: string;
    remove: string;
    rename: string;
    renameHint: string;
    addPlaceholder: string;
    text: string;
    voice: string;
    add: string;
    build: string;
    reset: string;
    counts: string;
    removed: string;
    renamed: string;
    added: string;
    duplicate: string;
    building: string;
    done: string;
  };
  themes: {
    title: string;
    label: string;
    sub: string;
    items: { id: string; label: string; blurb: string }[];
    rolesLabel: string;
    sharedLabel: string;
    mixNote: string;
  };
  rules: { title: string; label: string; sub: string };
  music: { title: string; label: string; body: string; points: string[] };
  pricing: {
    title: string;
    label: string;
    sub: string;
    plans: PlanCopy[];
    howTitle: string;
    how: string[];
    contact: string;
    note: string;
  };
  commands: { title: string; label: string; hint: string; copied: string; items: { name: string; args: string; d: string }[] };
  faq: { title: string; label: string; items: { q: string; a: string }[] };
  cta: { title: string; label: string; steps: string[]; button: string; setupId: string };
  footer: {
    word: string;
    line: string;
    privacy: string;
    terms: string;
    devlog: string;
    source: string;
    block: { project: string; drawn: string; stack: string; sheet: string; links: string };
  };
};
