import type { Dict } from "./types";

const vi: Dict = {
  lang: "vi",
  meta: {
    title: "Thầu Xây Dựng, bot Discord dựng cả server trong một lệnh",
    description:
      "Mời Thầu Xây Dựng vào server trống, gõ /build hoặc mô tả nhóm cho AI, xem bản vẽ, sửa, rồi xây. Có đủ kênh, role, luật và lời chào, tất cả đều hài hước.",
  },
  nav: {
    how: "Cách xây",
    themes: "Bản vẽ",
    pricing: "Gói",
    commands: "Lệnh",
    faq: "Hỏi đáp",
    devlog: "Nhật ký",
    cta: "Mời thầu vào server",
    switchTo: "EN",
    switchHref: "/en",
    theme: "Đổi giao diện sáng tối",
    home: "Về đầu trang",
  },
  hero: {
    title: "Server trống như ví cuối tháng.",
    sub: "Mời Thầu Xây Dựng vào, gõ /build hoặc mô tả nhóm của bạn cho AI. Vài phút sau server có đủ kênh, role, luật và vài lời chửi yêu, chưa kịp nghiệm thu nhưng cứ dùng đi.",
    cta: "Mời thầu vào server",
    secondary: "Xem công trình thi công",
    commandLabel: "Bản vẽ đang chờ lệnh",
    empty: "Chưa có kênh nào. Chưa có luật nào. Chưa có ai để cãi nhau.",
  },
  scene: {
    title: "Từ nền đất trống đến server hoàn chỉnh.",
    steps: [
      { t: "Gọi thầu", d: "Admin gõ /build và chọn một hay nhiều theme. Thầu gửi bản vẽ để duyệt trước, chưa đụng gì vào server." },
      { t: "Đổ móng role", d: "Chủ Tịch, Mod, Bot Nô Lệ và vài role xin về cho vui, mỗi role một cái tên không ai dám nhận là mình đặt." },
      { t: "Dựng kênh", d: "Danh mục, kênh chat, phòng voice, kênh của mod chỉ mod thấy. Kênh thông báo và luật khoá sẵn, người thường chỉ đọc." },
      { t: "Dán luật", d: "Luật, lời chào và bảng bấm nút xin role được đăng vào đúng kênh. Phòng DJ và phòng đọc chữ thành tiếng có sẵn nút mời bot." },
      { t: "Nghiệm thu", d: "Xong. Chạy lại /build sẽ không tạo trùng, và /nuke dọn đúng những gì thầu đã xây." },
    ],
    cmd: "/build theme: Game Thủ Cày Đêm",
    roles: "Role",
    rules: "Luật server",
    stamp: "Nghiệm thu",
    done: "xong",
  },
  ai: {
    title: "Gõ mô tả nhóm, AI dựng server riêng.",
    sub: "Không muốn dùng theme có sẵn? Kể cho thầu nghe nhóm bạn là ai, thích gì. AI của Google Gemini nghĩ ra danh mục, kênh, role, luật và lời chào hợp với nhóm đó, rồi bạn xem và sửa trước khi xây.",
    inputLabel: "Bạn gõ",
    description: "Nhóm 8 người bạn đại học, hay chơi Valorant tối thứ Bảy và tám chuyện",
    levelLabel: "Mức hài",
    levels: ["Nhẹ nhàng", "Troll", "Siêu nhảm"],
    resultLabel: "AI trả về",
    sampleNote: "Ví dụ thật từ một lần chạy ở mức Troll, đã rút gọn. Mỗi lần chạy ra một kết quả khác.",
    plan: "Có từ gói Pro. Mỗi server có hạn mức lượt AI mỗi tháng.",
  },
  editor: {
    title: "Xem trước, sửa, rồi mới xây.",
    sub: "Cả /build lẫn /thietke đều cho bạn thấy cả cây kênh trước khi tạo bất cứ thứ gì. Không có cú bấm nào làm server bạn biến dạng bất ngờ.",
    points: [
      { t: "Bỏ danh mục", d: "Không cần khu nào thì bỏ khỏi bản vẽ bằng một ô chọn." },
      { t: "Đổi tên", d: "Đổi tên danh mục cho hợp giọng nhóm bạn." },
      { t: "Thêm kênh", d: "Thêm kênh chat hoặc phòng voice của riêng bạn." },
      { t: "Xác nhận", d: "Chỉ người gọi lệnh, và phải là admin, mới bấm xây được. Bản vẽ tự hết hạn sau 15 phút." },
    ],
    mockLabel: "Bản vẽ: Tổ Đội Bắn Trượt",
    removeLabel: "Bỏ một danh mục",
    renameLabel: "Đổi tên một danh mục",
    add: "Thêm kênh",
    build: "Xây luôn đại ca",
    cancel: "Để tui nghĩ lại",
    footer: "6 danh mục, 24 kênh, 9 role. Bản vẽ hết hạn sau 15 phút.",
  },
  themes: {
    title: "Chọn một bản vẽ.",
    sub: "Bốn theme có sẵn. Phần chung (hành chính, phòng DJ, hậu trường mod) theme nào cũng có.",
    items: [
      { id: "gaming", label: "Game Thủ Cày Đêm", blurb: "Cho hội cày game: kênh tìm team, kênh khoe clip, kênh khóc lóc sau trận." },
      { id: "hoc-tap", label: "Học Mà Như Không Học", blurb: "Cho hội học nhóm: hỏi bài, deadline sắp cháy, phòng ôn đêm trước thi." },
      { id: "cong-dong", label: "Cộng Đồng Tạp Hoá", blurb: "Cho mọi loại cộng đồng: tám chuyện, khoe ảnh, sự kiện, đủ thứ lặt vặt." },
      { id: "chill-ban-be", label: "Chill Cùng Hội Bạn", blurb: "Cho nhóm bạn thân: kho ảnh xấu của nhau, kế hoạch đi chơi không bao giờ đi." },
    ],
    rolesLabel: "Role mẫu",
    channelsLabel: "Kênh riêng của theme",
    sharedLabel: "Phần chung",
    tablist: "Chọn theme",
    mixNote: "Vừa học vừa chơi vừa chill? Gói Pro cho trộn tới 4 theme trong một server, kênh trùng tên chỉ xuất hiện một lần.",
  },
  rules: {
    title: "Luật không ai đọc, nhưng ai cũng bị nhắc.",
    sub: "Tám luật chung và hai luật riêng cho mỗi theme, đăng sẵn vào kênh luật. Vài điều mẫu:",
  },
  music: {
    title: "Còn nhạc và đọc chữ thành tiếng thì sao?",
    body: "Discord không cho bot tự mời bot khác vào server, chỉ người thật mới bấm được. Nên thầu làm điều thầu làm được: dựng sẵn phòng DJ, phòng karaoke, phòng đọc chữ thành tiếng, và đặt nút mời bot nhạc, bot TTS ngay trong kênh. Admin bấm một lần là có nhạc.",
    points: ["#dj-booth có nút mời bot nhạc", "#chém-gió-bằng-giọng có nút mời bot TTS", "Link bot do bạn cấu hình, thầu chỉ đặt nút vào"],
  },
  pricing: {
    title: "Ba gói, trả theo server.",
    sub: "Mỗi server một gói. Mua mã kích hoạt, gõ /kichhoat, dùng ngay. Hết hạn thì server tự về gói miễn phí, những gì đã xây vẫn ở lại.",
    plans: [
      {
        id: "free",
        name: "Miễn phí",
        price: "0đ",
        blurb: "Để thử xem thầu làm ăn ra sao.",
        features: ["1 theme có sẵn", "Xây 1 lần", "Xem trước và sửa bản vẽ", "/nuke để dọn lại", "Không có AI"],
      },
      {
        id: "pro",
        name: "Pro",
        price: "Liên hệ",
        blurb: "Cho nhóm muốn server hợp với mình.",
        features: ["Trộn tới 4 theme", "Xây không giới hạn", "AI thiết kế: 20 lượt mỗi tháng", "Chọn mức hài", "Xem trước và sửa bản vẽ"],
      },
      {
        id: "plus",
        name: "Plus",
        price: "Liên hệ",
        blurb: "Cho người dựng nhiều server.",
        features: ["Mọi thứ của Pro", "AI thiết kế: 100 lượt mỗi tháng"],
      },
    ],
    howTitle: "Cách mua",
    how: ["Nhắn chủ bot, nói gói và số ngày bạn muốn", "Chuyển khoản theo hướng dẫn, nhận mã dạng THAU-XXXX-XXXX-XXXX", "Gõ /kichhoat ma:<mã> trong server. Mã chỉ dùng một lần, mã thứ hai cùng gói sẽ cộng thêm ngày"],
    contact: "Nhắn chủ bot để mua mã",
    note: "Giá chưa niêm yết cố định, chốt khi nhắn tin. Chưa có thanh toán tự động.",
  },
  commands: {
    title: "Bảy lệnh cho khách, không hơn.",
    items: [
      { name: "/build", args: "theme theme2 theme3 theme4", d: "Dựng server theo một hay nhiều theme. Có bản vẽ xem trước, sửa được, rồi mới xác nhận. Chỉ admin gọi được." },
      { name: "/thietke", args: "mota muc-do-hai", d: "AI thiết kế server riêng từ mô tả nhóm. Từ gói Pro, có hạn mức mỗi tháng." },
      { name: "/nuke", args: "", d: "Đập những gì thầu đã xây. Chỉ đụng kênh và role do bot tạo, có nút xác nhận." },
      { name: "/kichhoat", args: "ma", d: "Kích hoạt gói trả phí cho server bằng mã đã mua." },
      { name: "/goi", args: "", d: "Xem gói hiện tại, số lần đã xây và cách nâng cấp." },
      { name: "/xoadulieu", args: "", d: "Bot quên danh sách kênh và role đã xây. Kênh và role trên Discord vẫn còn." },
      { name: "/roast", args: "nguoi", d: "Roast nhẹ một thành viên cho vui. Không mod được, không mute được, chỉ mất lòng." },
    ],
  },
  faq: {
    title: "Hỏi đáp",
    items: [
      { q: "Bot cần quyền gì?", a: "Người gọi lệnh cần quyền Administrator. Bot cần quyền quản lý kênh, quản lý role và quản lý server, và cần đăng được vào các kênh khoá chỉ đọc. Cách dễ nhất là mời bot với quyền Administrator." },
      { q: "Thầu có xoá kênh sẵn có của tôi không?", a: "Không. /build chỉ thêm, kênh trùng tên bị bỏ qua. /nuke chỉ xoá những gì chính bot đã tạo, theo ID đã ghi lại." },
      { q: "Chạy /build hai lần có bị trùng không?", a: "Không. Phần đã có được bỏ qua, và nội dung như luật, lời chào không bị đăng lại. Nhưng gói miễn phí chỉ được xây một lần." },
      { q: "AI có tự xây thẳng vào server không?", a: "Không bao giờ. Kết quả của AI được lọc (bỏ mention, từ cấm, giới hạn số lượng) rồi hiện thành bản vẽ để bạn xem và sửa. Chỉ khi bạn bấm xây mới có gì được tạo." },
      { q: "Mô tả nhóm của tôi đi đâu?", a: "Đoạn mô tả bạn gõ được gửi tới Google Gemini để tạo bản thiết kế, không kèm tên người dùng hay tin nhắn. Bot dùng gói miễn phí của Google nên Google có thể dùng nội dung đó để cải thiện sản phẩm. Đừng viết thông tin riêng tư vào đó." },
      { q: "Bot lưu gì về server của tôi?", a: "ID các kênh và role mà bot đã tạo, gói đang dùng, và số lần dùng một số tính năng. Bot không đọc nội dung tin nhắn. Gõ /xoadulieu để bot quên danh sách đã xây." },
      { q: "Sao không tự có nhạc luôn?", a: "Vì Discord cấm bot tự mời bot. Thầu đặt sẵn nút mời trong kênh DJ, bạn bấm một lần là xong." },
    ],
  },
  cta: {
    title: "Server của bạn đã chờ đủ lâu rồi.",
    steps: ["Mời Thầu Xây Dựng vào server (cấp quyền Administrator cho khỏe)", "Gõ /build hoặc /thietke, xem bản vẽ, sửa nếu muốn", "Bấm xây luôn, đi pha cà phê"],
    button: "Mời thầu vào server",
    note: "",
    setupId: "cai-dat",
  },
  footer: {
    word: "XÂY XONG",
    privacy: "Quyền riêng tư",
    terms: "Điều khoản",
    devlog: "Nhật ký làm bot",
    source: "Mã nguồn",
    line: "Dự án cá nhân, không liên kết với Discord. Công trình hài hước, bảo hành không có.",
  },
};

export default vi;
