import type { Dict } from "./types";

const vi: Dict = {
  lang: "vi",
  meta: {
    title: "Thầu Xây Dựng, bot Discord dựng và trông coi cả server",
    description:
      "Mời Thầu Xây Dựng vào server trống, bấm nút Bắt đầu hoặc gõ /batdau, xem bản vẽ, rồi xây. Có đủ kênh, role, luật, chống raid, nhật ký quản trị, giveaway và báo cáo tuần, tất cả đều hài hước và không đọc tin nhắn của ai.",
  },
  nav: {
    how: "Cách xây",
    themes: "Bản vẽ",
    pricing: "Gói",
    commands: "Lệnh",
    faq: "Hỏi đáp",
    devlog: "Nhật ký",
    status: "Trạng thái",
    cta: "Mời thầu vào server",
    switchTo: "EN",
    switchHref: "/en",
    theme: "Đổi giao diện sáng tối",
    home: "Về đầu trang",
  },
  hero: {
    title: "Server trống như ví cuối tháng.",
    sub: "Mời Thầu Xây Dựng vào, bấm Bắt đầu hoặc gõ /batdau, hay mô tả nhóm của bạn cho AI. Vài phút sau server có đủ kênh, role, luật và vài lời chửi yêu, lại có người canh cổng khi bị raid. Chưa kịp nghiệm thu nhưng cứ dùng đi.",
    cta: "Mời thầu vào server",
    secondary: "Xem công trình thi công",
    dim: "1 lệnh, vài phút",
  },
  plotter: {
    title: "Bàn vẽ thử",
    chipsLabel: "Chọn theme, có thể trộn nhiều cái",
    hint: "Bấm để chọn hoặc bỏ theme. Cây bên dưới là kết quả thật của bot cho từng tổ hợp.",
    proNote: "Trộn nhiều theme là của gói Pro. Kênh trùng tên chỉ xuất hiện một lần.",
    limit: "Tối đa 4 theme một lần, giống lệnh /build.",
    categories: "danh mục",
    channels: "kênh",
    roles: "role",
    rules: "luật",
    build: "Xây thử",
    done: "Nghiệm thu",
    summary: "{categories} danh mục, {channels} kênh, {roles} role",
  },
  scene: {
    title: "Từ nền đất trống đến server hoàn chỉnh.",
    label: "Cách xây",
    steps: [
      { t: "Gọi thầu", d: "Admin gõ /build và chọn một hay nhiều theme. Thầu gửi bản vẽ để duyệt trước, chưa đụng gì vào server." },
      { t: "Đổ móng role", d: "Chủ Tịch, Mod, Bot Nô Lệ và vài role xin về cho vui, mỗi role một cái tên không ai dám nhận là mình đặt." },
      { t: "Dựng kênh", d: "Danh mục, kênh chat, phòng voice, kênh của mod chỉ mod thấy. Kênh thông báo và luật khoá sẵn, người thường chỉ đọc." },
      { t: "Dán luật", d: "Luật, lời chào và bảng bấm nút xin role được đăng vào đúng kênh. Phòng DJ và phòng đọc chữ thành tiếng có sẵn nút mời bot." },
      { t: "Nghiệm thu", d: "Xong. Chạy lại /build sẽ không tạo trùng, và /nuke dọn đúng những gì thầu đã xây." },
    ],
    cmd: "/build theme: Game Thủ Cày Đêm",
    roles: "Role",
    rules: "Luật server",
    stamp: "Nghiệm thu",
  },
  ai: {
    title: "Gõ mô tả nhóm, AI dựng server riêng.",
    label: "AI thiết kế",
    sub: "Không muốn dùng theme có sẵn? Kể cho thầu nghe nhóm bạn là ai, thích gì. AI của Google Gemini nghĩ ra danh mục, kênh, role, luật và lời chào hợp với nhóm đó, rồi bạn xem và sửa trước khi xây. Đổi mức hài bên dưới để xem ba kết quả thật.",
    inputLabel: "Bạn gõ",
    description: "Nhóm 8 người bạn đại học, hay chơi Valorant tối thứ Bảy và tám chuyện",
    levelLabel: "Mức hài",
    levels: ["Nhẹ nhàng", "Troll", "Siêu nhảm"],
    resultLabel: "AI trả về",
    provenance: "Cả ba là kết quả thật, chạy ngày {date} bằng {model}. Mỗi lần chạy ra một kết quả khác.",
    plan: "Có từ gói Pro. Mỗi server có hạn mức lượt AI mỗi tháng.",
  },
  editor: {
    title: "Xem trước, sửa, rồi mới xây.",
    label: "Bản vẽ",
    sub: "Cả /build lẫn /thietke đều cho bạn thấy cả cây kênh trước khi tạo bất cứ thứ gì. Bên cạnh là bản thu nhỏ chạy thật theo đúng luật của bot: thử bỏ một danh mục, đổi tên, thêm kênh rồi bấm xây.",
    points: [
      { t: "Bỏ danh mục", d: "Không cần khu nào thì bỏ khỏi bản vẽ. Riêng khu hành chính không bỏ được, vì luật và lời chào nằm ở đó." },
      { t: "Đổi tên", d: "Bấm vào tên danh mục để đổi cho hợp giọng nhóm bạn. Tên không được trùng nhau." },
      { t: "Thêm kênh", d: "Thêm kênh chat hoặc phòng voice của riêng bạn. Kênh trùng tên bị từ chối." },
      { t: "Xác nhận", d: "Chỉ người gọi lệnh, và phải là admin, mới bấm xây được. Bản vẽ tự hết hạn sau 15 phút." },
    ],
    tryLabel: "Thử ngay trên trang",
    locked: "cố định",
    remove: "Bỏ",
    rename: "Đổi tên danh mục",
    renameHint: "Bấm để đổi tên",
    addPlaceholder: "tên kênh mới",
    text: "chat",
    voice: "voice",
    add: "Thêm kênh",
    build: "Xây luôn đại ca",
    reset: "Làm lại bản vẽ",
    counts: "{c} danh mục, {ch} kênh",
    removed: "Đã bỏ {name}.",
    renamed: "Đã đổi tên danh mục.",
    added: "Đã thêm kênh {name}.",
    duplicate: "Tên trùng với cái đã có, giữ nguyên.",
    building: "Đang thi công...",
    done: "Xong, nghiệm thu.",
  },
  themes: {
    title: "Mười một bản vẽ có sẵn.",
    label: "Theme",
    sub: "Phần chung (hành chính, phòng DJ, hậu trường mod) theme nào cũng có. Mỗi theme thêm danh mục, kênh, role và hai điều luật riêng.",
    items: [
      { id: "gaming", label: "Game Thủ Cày Đêm", blurb: "Cho hội cày game: kênh tìm team, kênh khoe clip, kênh khóc lóc sau trận." },
      { id: "hoc-tap", label: "Học Mà Như Không Học", blurb: "Cho hội học nhóm: hỏi bài, deadline sắp cháy, phòng ôn đêm trước thi." },
      { id: "cong-dong", label: "Cộng Đồng Tạp Hoá", blurb: "Cho mọi loại cộng đồng: tám chuyện, khoe ảnh, sự kiện, đủ thứ lặt vặt." },
      { id: "chill-ban-be", label: "Chill Cùng Hội Bạn", blurb: "Cho nhóm bạn thân: kho ảnh xấu của nhau, kế hoạch đi chơi không bao giờ đi." },
      { id: "booking", label: "Booking Bạn Chơi", blurb: "Cho server thuê bạn chơi game hoặc tâm sự: hướng dẫn đặt lịch, bảng giá, hồ sơ player, feedback và chống lừa đảo." },
      { id: "anime", label: "Hội Mê Anime", blurb: "Cho hội cày anime và manga: gợi ý phim, review, spoiler có rào chắn, fanart và cãi nhau về waifu." },
      { id: "dev-code", label: "Hội Code Dạo", blurb: "Cho dân lập trình: hỏi bug, khoe project, review code, tìm việc và than về lần deploy chiều thứ Sáu." },
      { id: "creator", label: "Studio Content Creator", blurb: "Cho streamer, YouTuber, TikToker: ý tưởng, feedback video, lịch livestream, tìm collab và số liệu thật." },
      { id: "phim-nhac", label: "Rạp Phim Và Phòng Nhạc", blurb: "Cho hội xem phim, nghe nhạc: đề cử phim, bình chọn đêm xem chung, chia sẻ playlist và hát hò." },
      { id: "cong-so", label: "Văn Phòng Một Nhà", blurb: "Cho team công ty hoặc nhóm dự án: thông báo, việc hôm nay, deadline và chuyện tám giờ nghỉ trưa." },
      { id: "thu-cung", label: "Hội Yêu Thú Cưng", blurb: "Cho người nuôi chó mèo: khoe boss, hỏi cách chăm, tìm nhà cho bé và chuyện nhà các sen." },
    ],
    rolesLabel: "Role riêng",
    sharedLabel: "Phần chung",
    mixNote: "Vừa học vừa chơi vừa chill? Gói Pro cho trộn tới 4 theme trong một server. Thử ở bàn vẽ phía trên.",
  },
  features: {
    title: "Xây xong rồi, server vẫn sống.",
    label: "Sau khi xây",
    sub: "Dựng server mới chỉ là ngày đầu. Phần còn lại giữ cho server an toàn và nhóm của bạn ở lại: bảo vệ, quản trị, điểm hoạt động, giveaway, hộp góp ý, phòng thoại tạm, kênh thống kê, tin nhắn hẹn giờ, nhắc việc, báo cáo hằng tuần, mini-game và lịch định kỳ. Bot không đọc nội dung tin nhắn của ai.",
    items: [
      { t: "Dựng nhanh bằng /batdau", d: "Bot vào server là có nút Bắt đầu. Chọn kiểu server, giọng điệu và vài tính năng cần bật, bấm một nút: xong server, xong cài đặt, có điểm sức khoẻ trước và sau để khoe. Chưa biết chọn gì thì gõ vài chữ, thầu tự gợi ý." },
      { t: "Chống raid, khoá khẩn cấp", d: "Một đám người ùa vào cùng lúc? Thầu báo động ngay, rồi chỉ báo, nâng mức xác minh hoặc khoá kênh chat theo cách bạn chọn. Mọi thứ thầu đổi đều được ghi lại và tự trả về đúng như cũ khi hết giờ, hoặc bấm nút Mở khoá." },
      { t: "Chống xoá hàng loạt", d: "Ai đó xoá một loạt kênh hoặc role? Thầu đọc nhật ký kiểm tra để biết là ai, báo động và gỡ các role nguy hiểm của người đó. Không bao giờ đụng vào chủ server hay người ngang quyền bot. Gói Pro." },
      { t: "Nhật ký quản trị", d: "Ai bị cấm, ai được gỡ cấm, role nào bị đổi quyền (thêm gì, bớt gì), AutoMod chặn ai ở đâu. Ghi vào kênh bạn chọn, và không bao giờ ghi nội dung tin nhắn bị chặn." },
      { t: "Cảnh cáo, timeout, kick, ban có hồ sơ", d: "Bốn lệnh xử lý kiểm tra vai vế trước khi làm, nhắn riêng cho người bị xử, lưu một hồ sơ có số và ghi vào nhật ký. /hoso cho xem mười hồ sơ gần nhất của một người." },
      { t: "Điểm hoạt động và cấp độ", d: "Chat và ngồi voice đều lên cấp, có thời gian chờ và trần điểm mỗi ngày để không ai cày bằng spam. Bot chỉ biết ai nhắn ở đâu, không đọc chữ nào. Gói Pro." },
      { t: "Menu nhận role bằng nút", d: "Thành viên tự bấm nút để lấy hoặc bỏ role, chọn một hay chọn nhiều. Chỉ role an toàn mới vào được menu, và mỗi lần bấm đều được kiểm tra lại." },
      { t: "Giveaway và bình chọn", d: "Giveaway có nút Tham gia, role yêu cầu, nhiều người trúng, tự bốc thăm khi hết giờ và chọn lại được. Bình chọn ẩn danh bằng nút, mỗi người một phiếu, kết quả cập nhật tại chỗ." },
      { t: "Phòng thoại tạm", d: "Bước vào một phòng chờ là có ngay phòng thoại riêng mang tên bạn, chủ phòng tự đổi tên và mời người ra vào, phòng trống thì tự dọn. Thầu chỉ xoá những phòng nó tự tạo và đã ghi lại. Miễn phí 1 phòng chờ, Pro 3, Plus 5." },
      { t: "Kênh thống kê", d: "Một kênh thoại mà cái tên là con số thật: thành viên, lượt boost, số kênh, số role. Cập nhật mỗi 10 phút vì Discord giới hạn việc đổi tên kênh. Thầu có thể tự dựng kênh khoá cho bạn. Tối đa 4 kênh, miễn phí được 1." },
      { t: "Hộp góp ý", d: "Ai cũng gửi được góp ý, mọi người bấm vote lên hoặc xuống, quản lý bấm duyệt, từ chối hoặc đã làm kèm ghi chú, người gửi nhận tin nhắn riêng báo kết quả. Mỗi người một phiếu, có giới hạn chống spam. Miễn phí." },
      { t: "Nhắc việc riêng", d: "Gõ /nhacviec, chọn sau bao lâu hoặc lúc mấy giờ, thầu nhắn riêng nhắc bạn đúng lúc. Ai cũng dùng được, miễn phí. Không nhắn riêng được thì thầu nhắc ở kênh cũ và chỉ réo tên bạn." },
      { t: "Hẹn giờ đăng tin nhắn", d: "Một tin nhắn đăng đúng giờ mỗi ngày hoặc mỗi tuần: nhắc luật, chúc buổi sáng, lịch học. Không bao giờ ping ai, kể cả @everyone. Có xem thử trước khi hẹn. Pro 5 tin, Plus 15 tin." },
      { t: "Lọc tài khoản mới", d: "Đặt số ngày tối thiểu của tài khoản Discord. Ai vào mà tài khoản mới hơn mức đó thì thầu báo động, hoặc đuổi nếu bạn chọn vậy. Không bao giờ đuổi chủ server, bot hay người ngang quyền bot. Miễn phí." },
      { t: "Từ khoá chặn riêng", d: "Lập danh sách từ cấm của riêng server. Thầu ghi vào luật từ khoá gốc của Discord, Discord là bên chặn, bot không bao giờ thấy tin nhắn. Miễn phí 20 từ, Pro 200, Plus 500." },
      { t: "Bản tin tuần, khám định kỳ", d: "Mỗi tuần một tin tóm tắt gửi kênh mod: người mới vào, ticket, AutoMod chặn, điểm sức khoẻ so với tuần trước và ba việc nên làm. Điểm tụt mạnh thì có cảnh báo riêng. Chỉ đếm số, không đọc tin." },
      { t: "Nhắc trước khi hết hạn", d: "Gói Pro hoặc Plus sắp hết thì bot nhắc một lần trước 3 ngày và một lần khi hết hạn, không làm phiền thêm. Gia hạn thì ngày được cộng nối vào." },
      { t: "Trợ lý viết giúp", d: "Không biết viết luật, lời chào, thông báo? Mô tả vài chữ, AI viết bản nháp. Thầu không tự đăng gì, bạn đọc và bấm đăng. Có cả giải thích kết quả khám sức khoẻ bằng lời dễ hiểu. Gói Pro." },
      { t: "Ba mức hài", d: "Cùng một server, ba giọng: nhẹ nhàng, troll, siêu nhảm. Luật chung và lời chào đổi giọng, cấu trúc kênh giữ nguyên nên xây lại ở mức khác không bị trùng." },
      { t: "Theme riêng", d: "Sửa bản vẽ xong, bấm lưu thành theme của bạn. Dùng lại, xuất ra file hoặc nhập từ bạn bè. Theme riêng không bao giờ mang quyền." },
      { t: "Backup và khôi phục", d: "Chụp lại cấu trúc server: role, kênh, quyền. Khôi phục chỉ tạo phần còn thiếu, không xoá gì, và không bao giờ cấp quyền Administrator." },
      { t: "Điểm danh, level, mini-game", d: "Điểm danh mỗi ngày, lên cấp theo điểm, đoán số, kéo búa bao và câu hỏi nhanh. Có bảng xếp hạng cho cả nhóm." },
      { t: "Sự kiện định kỳ", d: "Hẹn tối thứ Sáu chơi game, Chủ nhật học nhóm: bot tự tạo sự kiện Discord và nhắc trước." },
      { t: "Thanh toán tự động", d: "Gõ /mua, trả bằng thẻ (Stripe) hoặc quét mã QR ngân hàng Việt Nam (payOS), gói tự bật khi tiền về. Không phải chờ ai gửi mã." },
      { t: "Chào người mới", d: "Người mới vào là có lời chào hài hước, role mới và nút xác nhận mình là người. Bot chỉ đọc thông báo tham gia của Discord, không đọc tin nhắn của ai." },
      { t: "Khám sức khoẻ server", d: "Quét server đang chạy và chấm điểm: @everyone có quyền nguy hiểm, thiếu luật, kênh thông báo ai cũng viết được. Lỗi nào sửa được an toàn thì có nút sửa, bạn xem trước đúng những gì sẽ đổi." },
      { t: "AutoMod gốc của Discord", d: "Thầu cài AutoMod có sẵn của Discord ở ba mức, với lời chặn hài hước. Bot không bao giờ phải đọc nội dung tin nhắn." },
      { t: "Bảng điều khiển trên web", d: "Đăng nhập bằng Discord, chọn server của bạn và chỉnh lời chào, AutoMod, ticket, bảo vệ, điểm hoạt động, báo cáo tuần, nhật ký quản trị, xem điểm sức khoẻ ngay trên trình duyệt. Chỉ quản trị viên của server mới thấy server đó." },
      { t: "Ticket hỗ trợ", d: "Bảng nút mở ticket, kênh riêng cho người hỏi và nhân viên, nhận và đóng ticket, tự đóng khi im lặng. Không lưu nội dung chat." },
      { t: "Xem nhanh mọi lệnh", d: "/trogiup liệt kê lệnh chia theo nhóm, ghi rõ lệnh nào thuộc gói cao hơn, kèm đường dẫn tới sổ tay." },
    ],
  },
  rules: {
    title: "Luật không ai đọc, nhưng ai cũng bị nhắc.",
    label: "Luật",
    sub: "Tám luật chung và hai luật riêng cho mỗi theme, đăng sẵn vào kênh luật. Vài điều mẫu:",
  },
  music: {
    title: "Còn nhạc và đọc chữ thành tiếng thì sao?",
    label: "Nhạc và TTS",
    body: "Discord không cho bot tự mời bot khác vào server, chỉ người thật mới bấm được. Nên thầu làm điều thầu làm được: dựng sẵn phòng DJ, phòng karaoke, phòng đọc chữ thành tiếng, và đặt nút mời bot nhạc, bot TTS ngay trong kênh. Admin bấm một lần là có nhạc.",
    points: ["#dj-booth có nút mời bot nhạc", "#chém-gió-bằng-giọng có nút mời bot TTS", "Link bot do bạn cấu hình, thầu chỉ đặt nút vào"],
  },
  pricing: {
    title: "Ba gói, trả theo server.",
    label: "Gói",
    sub: "Mỗi server một gói. Trả bằng thẻ hoặc QR ngân hàng, gói tự bật khi tiền về. Hết hạn thì server tự về gói miễn phí, những gì đã xây vẫn ở lại.",
    plans: [
      {
        id: "free",
        name: "Miễn phí",
        price: "$0",
        blurb: "Để thử xem thầu làm ăn ra sao.",
        features: ["1 theme có sẵn, xây 2 lần", "Dựng nhanh bằng /batdau", "Xem trước và sửa bản vẽ", "/nuke để dọn lại", "Chào người mới", "Khám sức khoẻ server", "AutoMod cơ bản", "Chống raid, khoá khẩn cấp, nhật ký quản trị", "Cảnh cáo, timeout, kick, ban có hồ sơ", "Bình chọn, bản tin tuần", "3 menu nhận role", "Hộp góp ý, nhắc việc riêng", "Phòng thoại tạm (1 phòng chờ), 1 kênh thống kê", "Lọc tài khoản mới", "20 từ khoá chặn riêng", "Không có AI"],
      },
      {
        id: "pro",
        name: "Pro",
        price: "$3.99 / 30 ngày",
        blurb: "Cho nhóm muốn server hợp với mình.",
        features: ["Trộn tới 4 theme, xây không giới hạn", "AI thiết kế: 20 lượt mỗi tháng", "Trợ lý viết giúp /vietgiup", "Chọn mức hài", "Chống xoá hàng loạt", "Điểm hoạt động chat và voice", "Giveaway", "10 menu nhận role", "3 phòng chờ, 4 kênh thống kê", "5 tin nhắn hẹn giờ", "200 từ khoá chặn riêng", "3 bản backup, 3 theme riêng", "Mini-game, level, bảng xếp hạng", "3 sự kiện định kỳ", "AutoMod ba mức, chặn link", "Ticket hỗ trợ"],
      },
      {
        id: "plus",
        name: "Plus",
        price: "$7.99 / 30 ngày",
        blurb: "Cho người dựng nhiều server.",
        features: ["Mọi thứ của Pro", "AI thiết kế: 100 lượt mỗi tháng", "25 menu nhận role", "5 phòng chờ", "15 tin nhắn hẹn giờ", "500 từ khoá chặn riêng", "10 bản backup", "10 theme riêng", "10 sự kiện định kỳ"],
      },
    ],
    options: [
      { t: "Mua một năm, trả mười tháng", d: "Chọn 365 ngày: Pro 39,90 đô, Plus 79,90 đô. Tặng hai tháng. Cũng có 90 và 180 ngày." },
      { t: "Dựng giúp, 4,99 đô một lần", d: "Không muốn đăng ký? Trả một lần, nhận 7 ngày Pro, đủ để dựng và cài xong cả server. Chọn ở lệnh /mua." },
      { t: "Dùng thử Pro 7 ngày miễn phí", d: "Gõ /dungthu, mỗi server một lần, không cần thẻ, không tự gia hạn." },
    ],
    howTitle: "Cách mua",
    how: ["Gõ /mua trong server của bạn (chỉ admin gõ được), chọn Pro, Plus hoặc Dựng giúp và 30, 90, 180 hoặc 365 ngày", "Bấm nút Thanh toán, nhập thẻ trên trang của Stripe hoặc quét mã QR bằng app ngân hàng", "Tiền về là gói tự bật trong chừng một phút, không cần nhập mã"],
    contact: "Muốn mua bằng mã? Nhắn Instagram",
    note: "Giá bằng đô la Mỹ, mỗi server, mỗi 30 ngày, một năm tính 10 tháng. Thanh toán bằng VND theo tỷ giá thầu cập nhật, giá hiện trước khi bạn bấm trả. Cách khác: nhắn Instagram để nhận mã dạng THAU-XXXX-XXXX-XXXX rồi gõ /kichhoat.",
  },
  commands: {
    title: "Các lệnh của thầu.",
    label: "Lệnh",
    hint: "bấm để chép",
    copied: "đã chép",
    items: [
      { name: "/batdau", args: "", d: "Dựng và cài đặt cả server bằng ba ô chọn và một nút: kiểu server, giọng điệu, tính năng cần bật. Chỉ admin gọi được." },
      { name: "/trogiup", args: "", d: "Danh sách lệnh chia theo nhóm, lệnh nào thuộc gói cao hơn thì ghi rõ, kèm nút mở sổ tay." },
      { name: "/build", args: "theme theme2 theme3 theme4 muc-do-hai", d: "Dựng server theo một hay nhiều theme, ở mức hài bạn chọn. Có bản vẽ xem trước, sửa được, rồi mới xác nhận. Chỉ admin gọi được." },
      { name: "/thietke", args: "mota muc-do-hai", d: "AI thiết kế server riêng từ mô tả nhóm. Từ gói Pro, có hạn mức mỗi tháng." },
      { name: "/vietgiup", args: "luat loichao thongbao giaithich", d: "AI viết bản nháp luật, lời chào, thông báo, hoặc giải thích kết quả khám sức khoẻ. Không tự đăng. Từ gói Pro." },
      { name: "/theme", args: "danhsach dung xoa xuat nhap", d: "Dùng lại, xuất và nhập theme riêng đã lưu từ bản vẽ. Từ gói Pro." },
      { name: "/backup", args: "tao khoiphuc danhsach xoa xuat nhap", d: "Sao lưu cấu trúc server và khôi phục phần còn thiếu. Từ gói Pro." },
      { name: "/sukien", args: "tao danhsach xoa mau", d: "Tạo sự kiện định kỳ hằng tuần, bot tự lên lịch và nhắc. Từ gói Pro." },
      { name: "/diemdanh", args: "", d: "Điểm danh mỗi ngày để nhận điểm và giữ chuỗi. Từ gói Pro." },
      { name: "/bangxephang", args: "loai", d: "Xem top 10 điểm vui hoặc điểm hoạt động của server và cấp bậc của từng người." },
      { name: "/doanso", args: "so", d: "Đoán số từ 1 đến 100, cả server cùng đoán, ai trúng được điểm." },
      { name: "/thachdau", args: "nguoi", d: "Thách ai đó kéo búa bao, người thắng được điểm." },
      { name: "/cauhoi", args: "", d: "Câu hỏi nhanh bốn đáp án, ai bấm đúng đầu tiên được điểm." },
      { name: "/hang", args: "xem caidat", d: "Xem cấp độ, điểm và hạng hoạt động (chat và voice). Admin bật và chỉnh số điểm. Từ gói Pro." },
      { name: "/vaitro", args: "tao dang danhsach xoa", d: "Menu nhận role bằng nút, chọn một hay nhiều. Admin tạo. Gói miễn phí 3 menu, Pro 10, Plus 25." },
      { name: "/quatang", args: "tao huy chonlai danhsach", d: "Giveaway có nút Tham gia, tự bốc thăm khi hết giờ, chọn lại được. Cần quyền Quản lý server. Từ gói Pro." },
      { name: "/binhchon", args: "cauhoi lua1 lua2 thoigian", d: "Bình chọn ẩn danh bằng nút, mỗi người một phiếu, đóng bằng giờ hoặc bằng nút. Cần quyền Quản lý tin nhắn." },
      { name: "/phongtam", args: "caidat them bo trangthai tat", d: "Phòng thoại tạm: bước vào phòng chờ là có phòng riêng, trống thì tự dọn. Admin cài đặt. Miễn phí 1 phòng chờ, Pro 3, Plus 5." },
      { name: "/kenhthongke", args: "them xoa danhsach tat", d: "Kênh thoại hiện số thành viên, boost, kênh hoặc role, cập nhật mỗi 10 phút. Admin cài đặt. Miễn phí 1 kênh, Pro và Plus 4." },
      { name: "/gopy", args: "gui caidat danhsach xoa", d: "Hộp góp ý của server: ai cũng gửi được, mọi người vote, quản lý duyệt. Cài đặt cần quyền Quản lý server. Miễn phí." },
      { name: "/nhacviec", args: "tao danhsach xoa", d: "Nhờ thầu nhắc việc riêng qua tin nhắn riêng, sau một lúc hoặc vào một giờ. Ai cũng dùng được. Miễn phí." },
      { name: "/hengio", args: "tao danhsach xoa thu", d: "Hẹn giờ đăng tin nhắn mỗi ngày hoặc mỗi tuần, không ping ai, có xem thử. Admin dùng. Pro 5 tin, Plus 15 tin." },
      { name: "/chaomung", args: "caidat thu tat", d: "Chào người mới bằng lời hài hước, cấp role mới và nút xác nhận. Admin cài đặt." },
      { name: "/khamsuckhoe", args: "kiemtra lichsu", d: "Quét server và chấm điểm sức khoẻ, kèm nút sửa an toàn có xem trước." },
      { name: "/automod", args: "bat tat trangthai mientru tukhoa", d: "Cài AutoMod gốc của Discord ở ba mức, và lập danh sách từ khoá chặn riêng (tukhoa them, xoa, danhsach, xoahet) do Discord tự chặn. Mức gắt, chặn link và miễn trừ là của gói Pro. Từ khoá: Miễn phí 20, Pro 200, Plus 500." },
      { name: "/khoakhan", args: "bat tat trangthai caidat nhatky", d: "Khoá khẩn cấp, chống raid tự động, lọc tài khoản mới tạo, chống xoá hàng loạt (Pro) và nhật ký quản trị. Mọi thứ khoá đều tự mở đúng như cũ." },
      { name: "/canhcao", args: "nguoi lydo", d: "Cảnh cáo một thành viên và ghi vào hồ sơ. Cần quyền Timeout thành viên." },
      { name: "/timeout", args: "nguoi thoigian lydo", d: "Bắt một thành viên ngồi im từ một phút đến một tuần, ghi vào hồ sơ. Cần quyền Timeout thành viên." },
      { name: "/kick", args: "nguoi lydo", d: "Đuổi một thành viên ra khỏi server, ghi vào hồ sơ. Cần quyền Đuổi thành viên." },
      { name: "/ban", args: "nguoi lydo xoatin", d: "Cấm một người, có thể xoá tin nhắn gần đây của họ, ghi vào hồ sơ. Cần quyền Cấm thành viên." },
      { name: "/hoso", args: "nguoi", d: "Xem mười hồ sơ vi phạm gần nhất của một thành viên. Cần quyền Timeout thành viên." },
      { name: "/ticket", args: "caidat loai dang danhsach tat", d: "Hệ thống ticket hỗ trợ với bảng nút, kênh riêng và tự đóng. Từ gói Pro." },
      { name: "/nuke", args: "", d: "Đập những gì thầu đã xây. Chỉ đụng kênh và role do bot tạo, có nút xác nhận." },
      { name: "/mua", args: "goi ngay cach", d: "Mua hoặc gia hạn Pro, Plus hoặc gói Dựng giúp bằng thẻ hoặc QR ngân hàng, gói tự bật khi tiền về." },
      { name: "/dungthu", args: "", d: "Dùng thử gói Pro 7 ngày miễn phí, mỗi server một lần." },
      { name: "/kichhoat", args: "ma", d: "Kích hoạt gói trả phí cho server bằng mã đã mua." },
      { name: "/goi", args: "", d: "Xem gói hiện tại, số lần đã xây, bảng giá và cách nâng cấp." },
      { name: "/xoadulieu", args: "", d: "Bot quên mọi dữ liệu về server, gồm cả phòng tạm, tin hẹn giờ, lời nhắc và góp ý, trừ gói và đơn thanh toán. Kênh và role trên Discord vẫn còn." },
      { name: "/roast", args: "nguoi", d: "Roast nhẹ một thành viên cho vui. Không mod được, không mute được, chỉ mất lòng." },
    ],
  },
  faq: {
    title: "Hỏi đáp",
    label: "Hỏi đáp",
    items: [
      { q: "Thầu có đọc tin nhắn của tôi không?", a: "Không. Bot không đọc, không lưu nội dung tin nhắn và không dùng quyền đọc nội dung (Message Content) và không dùng intent đặc quyền nào của Discord. Điểm hoạt động chỉ dùng việc ai nhắn ở kênh nào, nhật ký AutoMod ghi luật nào chặn ai mà không ghi chữ bị chặn, bản tin tuần chỉ đếm số." },
      { q: "/batdau là gì?", a: "Là cách dựng nhanh nhất: bot vào server sẽ đăng nút Bắt đầu, hoặc bạn gõ /batdau. Chọn kiểu server, giọng điệu và vài tính năng cần bật (chào người mới, AutoMod nhẹ, khám sức khoẻ hằng tuần, bảo vệ cơ bản, bản tin tuần), bấm Dựng luôn. Bot khám trước, dựng, bật tính năng, khám lại và đưa một thẻ kết quả có điểm trước và sau. Chạy lại không dựng trùng." },
      { q: "Chống raid làm gì với server của tôi?", a: "Nó đếm số người mới vào trong một khoảng thời gian ngắn (qua thông báo tham gia của Discord). Vượt ngưỡng bạn đặt thì báo động, và tuỳ cài đặt chỉ báo, nâng mức xác minh lên một bậc hoặc khoá kênh chat. Mọi thứ thầu đổi đều được ghi lại, tự trả về đúng như cũ khi hết giờ hoặc khi bạn bấm Mở khoá. Kênh bị ai chỉnh tay trong lúc khoá thì thầu không đụng vào." },
      { q: "Chống xoá hàng loạt có tự cấm người ta không?", a: "Không cấm. Khi một người xoá liên tiếp nhiều kênh hoặc role, thầu báo động và gỡ các role nguy hiểm của người đó (cần quyền xem nhật ký kiểm tra). Chủ server, bot và người ngang quyền bot thì không bị đụng tới. Tính năng này thuộc gói Pro." },
      { q: "Bot bao nhiêu tiền một tháng?", a: "Pro 3,99 đô và Plus 7,99 đô mỗi server mỗi 30 ngày. Mua một năm chỉ trả 10 tháng. Có gói Dựng giúp 4,99 đô trả một lần, nhận 7 ngày Pro. Gói miễn phí vẫn có dựng nhanh, chống raid, nhật ký quản trị và các lệnh xử lý thành viên, và xây được hai lần." },
      { q: "Bot cần quyền gì?", a: "Người gọi lệnh cần quyền Administrator. Bot cần quyền quản lý kênh, quản lý role và quản lý server, và cần đăng được vào các kênh khoá chỉ đọc. Cách dễ nhất là mời bot với quyền Administrator." },
      { q: "Thầu có xoá kênh sẵn có của tôi không?", a: "Không. /build và /batdau chỉ thêm, kênh trùng tên bị bỏ qua. /nuke chỉ xoá những gì chính bot đã tạo, theo ID đã ghi lại." },
      { q: "Chạy /build hai lần có bị trùng không?", a: "Không. Phần đã có được bỏ qua, và nội dung như luật, lời chào không bị đăng lại. Gói miễn phí được xây hai lần, chạy lại đúng cấu hình đã xây không tốn lượt." },
      { q: "AI có tự xây thẳng vào server không?", a: "Không bao giờ. Kết quả của AI được lọc (bỏ mention, từ cấm, giới hạn số lượng) rồi hiện thành bản vẽ để bạn xem và sửa. Chỉ khi bạn bấm xây mới có gì được tạo. Trợ lý /vietgiup cũng chỉ viết bản nháp cho bạn, không tự đăng." },
      { q: "Mô tả nhóm của tôi đi đâu?", a: "Đoạn mô tả bạn gõ vào /thietke hoặc /vietgiup được gửi tới Google Gemini để tạo bản thiết kế hay bản nháp, không kèm tên người dùng hay tin nhắn. Bot dùng gói miễn phí của Google nên Google có thể dùng nội dung đó để cải thiện sản phẩm. Đừng viết thông tin riêng tư vào đó." },
      { q: "Bot lưu gì về server của tôi?", a: "ID các kênh và role mà bot đã tạo, cài đặt các công cụ, gói đang dùng và số lần dùng. Khi bạn bật các tính năng mới còn có điểm hoạt động theo ID thành viên, hồ sơ xử lý, người tham gia giveaway, phiếu bình chọn, menu role, bản ghi phòng thoại tạm, tin nhắn hẹn giờ, lời nhắc riêng và góp ý kèm phiếu vote. Xem trang quyền riêng tư để biết đủ. Bot không đọc nội dung tin nhắn. Gõ /xoadulieu để bot quên danh sách đã xây và cài đặt." },
      { q: "Từ khoá chặn riêng có nghĩa là bot đọc tin nhắn không?", a: "Không. Thầu chỉ ghi danh sách từ vào luật từ khoá gốc của Discord. Discord tự chặn tin có từ đó trước khi ai thấy, còn bot không bao giờ nhận được tin nhắn. Danh sách từ bạn gõ được lưu trong cài đặt của server." },
      { q: "Phòng thoại tạm có xoá nhầm kênh của tôi không?", a: "Không. Mỗi phòng thầu tạo đều được ghi lại, và thầu chỉ xoá những phòng nằm trong sổ đó khi chúng trống. Kênh bạn tự làm, kể cả kênh tên giống, không bao giờ bị đụng tới." },
      { q: "Tin nhắn hẹn giờ có ping cả server được không?", a: "Không. Tin hẹn giờ không bao giờ ping ai, kể cả khi nội dung có @everyone hay tên role. Muốn gọi cả nhóm thì đăng tay." },
      { q: "Sao không tự có nhạc luôn?", a: "Vì Discord cấm bot tự mời bot. Thầu đặt sẵn nút mời trong kênh DJ, bạn bấm một lần là xong." },
    ],
  },
  cta: {
    title: "Server của bạn đã chờ đủ lâu rồi.",
    label: "Bắt đầu",
    steps: ["Mời Thầu Xây Dựng vào server (cấp quyền Administrator cho khỏe)", "Bấm nút Bắt đầu bot vừa đăng, hoặc gõ /batdau, chọn vài ô", "Bấm Dựng luôn, đi pha cà phê. Muốn tự sửa bản vẽ thì dùng /build hoặc /thietke"],
    button: "Mời thầu vào server",
    setupId: "cai-dat",
  },
  themePage: {
    open: "Xem cây kênh đầy đủ",
    back: "Tất cả theme",
    label: "Bản vẽ",
    ownRoles: "Role riêng của theme",
    sharedRoles: "Role chung của mọi server",
    tree: "Cây kênh",
    treeLede: "Đây là cây kênh thật mà bot dựng khi chọn riêng theme này. Tên kênh luôn bằng tiếng Việt.",
    voice: "phòng voice",
    staffOnly: "chỉ mod thấy",
    counts: "{categories} danh mục, {channels} kênh, {roles} role, {rules} luật",
    invite: "Mời thầu dựng theme này",
    inviteHint: "Mời bot, rồi gõ /batdau hoặc /build và chọn theme này.",
    cmdLabel: "Lệnh để dựng",
    prev: "Theme trước",
    next: "Theme sau",
    mix: "Trộn thêm theme khác trên bàn vẽ ở trang chủ (gói Pro).",
    seeAll: "Xem mười một theme",
    metaTitle: "{label}, theme Discord của Thầu Xây Dựng",
  },
  status: {
    title: "Thầu đang làm việc chưa?",
    label: "Trạng thái",
    sub: "Trang này hỏi thẳng bot ngay trong trình duyệt của bạn. Nếu bot không trả lời, trang chỉ nói là không kiểm tra được, chưa chắc bot đã hỏng.",
    checking: "Đang kiểm tra...",
    ok: "Đang làm việc",
    slow: "Bot trả lời nhưng nhịp tim đã cũ, có thể vừa khởi động lại",
    unknown: "không kiểm tra được",
    unknownHint: "Trình duyệt không hỏi được bot lúc này. Thử tải lại sau ít phút.",
    fields: { version: "Phiên bản", uptime: "Đã chạy liên tục", servers: "Số server", heartbeat: "Nhịp tim cuối" },
    servers: "khoảng {n}",
    ago: "{n} giây trước",
    uptime: { d: "ngày", h: "giờ", m: "phút", s: "giây" },
    retry: "Kiểm tra lại",
    note: "Số server được làm tròn xuống chục. Trang không lưu gì và không có ID hay tên server nào.",
    back: "Về trang chủ",
  },
  footer: {
    word: "XÂY XONG",
    privacy: "Quyền riêng tư",
    terms: "Điều khoản",
    devlog: "Nhật ký kỹ thuật",
    source: "Mã nguồn",
    line: "Dự án cá nhân, không liên kết với Discord. Công trình hài hước, bảo hành không có.",
    block: { project: "Dự án", drawn: "Vẽ bởi", stack: "Công nghệ", sheet: "Tờ", links: "Liên kết" },
  },
};

export default vi;
